#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace SuperGameEngine
{
    /// <summary>
    /// The top level type of a given asset.
    /// </summary>
    enum class GameAssetType : uint8_t
    {
        /// <summary>
        /// Only used for unsuccessful parsing.
        /// </summary>
        Unknown = 0,

        /// <summary>
        /// Asset represents an image.
        /// </summary>
        Texture,
    };

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EGameAssetType
    {
    public:
        static GameAssetType Min() { return GameAssetType::Texture; }
        static GameAssetType Max() { return GameAssetType::Texture; }

        static GameAssetType* ToArray()
        {
            static GameAssetType returnArray[] =
            {
                GameAssetType::Texture,
            };
            
            return returnArray;
        }

        static std::vector<GameAssetType> ToVector()
        {
            static std::vector<GameAssetType> returnVector =
            {
                GameAssetType::Texture,
            };
            
            return returnVector;
        }

        static std::string ToString(GameAssetType value)
        {
            switch (value)
            {
                case GameAssetType::Unknown: return "Unknown";
                case GameAssetType::Texture: return "Texture";
            }
            
            return "Unknown";
        }

        static GameAssetType FromString(std::string value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "Unknown") return GameAssetType::Unknown;
                if (value == "Texture") return GameAssetType::Texture;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "unknown") return GameAssetType::Unknown;
                if (valueLower == "texture") return GameAssetType::Texture;
            }
            
            return GameAssetType::Unknown;
        }

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
