#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace SuperGameTools
{
    /// <summary>
    /// Describes the selection state of the given draw bundle so that it maybe rendered correctly.
    /// </summary>
    enum class DrawBundleSelectionState : uint8_t
    {
        /// <summary>
        /// No cursor is interacting and the object for this bundle is not selected.
        /// </summary>
        NoInteraction = 0,

        /// <summary>
        /// The bundle has either a mouse cursor or other method to demostrate it could be selected on a key press.
        /// </summary>
        Hover = 1 << 0,

        /// <summary>
        /// The selection key is down over the object.
        /// </summary>
        SelectionKeyDown = 1 << 1,

        /// <summary>
        /// The object for the bundle is currently selected.
        /// </summary>
        Selected = 1 << 2,
    };

    /// <summary>
    /// Combines flags. For example: auto var = left | right; returns a bitflag containing both left and right. 
    /// </summary>
    inline DrawBundleSelectionState operator | (DrawBundleSelectionState lhs, DrawBundleSelectionState rhs)
    {
        using T = std::underlying_type_t <DrawBundleSelectionState>;
        return static_cast<DrawBundleSelectionState>(static_cast<T>(lhs) | static_cast<T>(rhs));
    }

    /// <summary>
    /// Combines flags in assignment. For example: left |= right; Adds right flag to left variable. 
    /// </summary>
    inline DrawBundleSelectionState& operator |= (DrawBundleSelectionState& lhs, DrawBundleSelectionState rhs)
    {
        lhs = lhs | rhs;
        return lhs;
    }

    /// <summary>
    /// Gets the intersection of flags. Mostly used as in this example: bool isSet = ((state & flag1) == flag1); 
    /// Is set would be true if state has the flag. Also this can be combined with ~ to remove a flag (see below). 
    /// HasFlag will also do this for you in nicer syntax. 
    /// </summary>
    inline DrawBundleSelectionState operator & (DrawBundleSelectionState lhs, DrawBundleSelectionState rhs)
    {
        using T = std::underlying_type_t <DrawBundleSelectionState>;
        return static_cast<DrawBundleSelectionState>(static_cast<T>(lhs) & static_cast<T>(rhs));
    }

    /// <summary>
    /// Returns the intersection of the flags in an assignment. 
    /// Mostly combined with ~ as in this example: state &= ~flagToRemove; 
    /// This would remove flagToRemove from the given state. 
    /// </summary>
    inline DrawBundleSelectionState& operator &= (DrawBundleSelectionState& lhs, DrawBundleSelectionState rhs)
    {
        lhs = lhs & rhs;
        return lhs;
    }

    /// <summary>
    /// Performs an XOR operation on the left and right and returns the result. 
    /// This is mostly which to compare two sets of flags and to figure out where they differ. 
    /// left = flag1; right = flag1 | flag2; different = left ^ right; 
    /// different in this example will be flag2.
    /// Keep in mind you would not know where the differences are you would need to do this: 
    /// bool checkLeft = different & left; - nothing removed / added. 
    /// bool checkRight = different & right; - flag2 added. 
    /// </summary>
    inline DrawBundleSelectionState operator ^ (DrawBundleSelectionState lhs, DrawBundleSelectionState rhs)
    {
        using T = std::underlying_type_t <DrawBundleSelectionState>;
        return static_cast<DrawBundleSelectionState>(static_cast<T>(lhs) ^ static_cast<T>(rhs));
    }

    /// <summary>
    /// Performs an XOR operation on the flag which results in a toggle assignment.
    /// Example: state ^= flag1; This would toggle whether flag1 is on within the enum.
    /// </summary>
    inline DrawBundleSelectionState& operator ^= (DrawBundleSelectionState& lhs, DrawBundleSelectionState rhs)
    {
        lhs = lhs ^ rhs;
        return lhs;
    }

    /// <summary>
    /// Returns the opposite or 'unset' or 'invert' flag of the given. 
    /// Mostly combined with &= as in this example: state &= ~flagToRemove; 
    /// This would remove flagToRemove from the given state. 
    /// </summary>
    inline DrawBundleSelectionState operator ~ (DrawBundleSelectionState lhs)
    {
        using T = std::underlying_type_t <DrawBundleSelectionState>;
        return static_cast<DrawBundleSelectionState>(~static_cast<T>(lhs));
    }

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EDrawBundleSelectionState
    {
    public:
        static DrawBundleSelectionState Min() { return DrawBundleSelectionState::NoInteraction; }
        static DrawBundleSelectionState Max() { return DrawBundleSelectionState::Selected; }

        static DrawBundleSelectionState* ToArray()
        {
            static DrawBundleSelectionState returnArray[] =
            {
                DrawBundleSelectionState::NoInteraction,
                DrawBundleSelectionState::Hover,
                DrawBundleSelectionState::SelectionKeyDown,
                DrawBundleSelectionState::Selected,
            };
            
            return returnArray;
        }

        static std::vector<DrawBundleSelectionState> ToVector()
        {
            static std::vector<DrawBundleSelectionState> returnVector =
            {
                DrawBundleSelectionState::NoInteraction,
                DrawBundleSelectionState::Hover,
                DrawBundleSelectionState::SelectionKeyDown,
                DrawBundleSelectionState::Selected,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "NoInteraction",
                "Hover",
                "SelectionKeyDown",
                "Selected",
            };
            
            return returnVector;
        }

        static std::string ToString(DrawBundleSelectionState value)
        {
            if(value == DrawBundleSelectionState::NoInteraction)
            {
                return "NoInteraction";
            }
            
            std::vector<std::string> entries;
            if(HasFlag(value,DrawBundleSelectionState::NoInteraction))
            {
                entries.emplace_back("NoInteraction");
            }
            if(HasFlag(value,DrawBundleSelectionState::Hover))
            {
                entries.emplace_back("Hover");
            }
            if(HasFlag(value,DrawBundleSelectionState::SelectionKeyDown))
            {
                entries.emplace_back("SelectionKeyDown");
            }
            if(HasFlag(value,DrawBundleSelectionState::Selected))
            {
                entries.emplace_back("Selected");
            }
            
            std::string returnToString = {};
            for (const std::string& entry : entries)
            {
                if (returnToString.empty())
                {
                    returnToString = entry;
                }
                else
                {
                    returnToString += " | " + entry;
                }
            }
            return returnToString;
        }

        static DrawBundleSelectionState FromString(const std::string& value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "NoInteraction") return DrawBundleSelectionState::NoInteraction;
                if (value == "Hover") return DrawBundleSelectionState::Hover;
                if (value == "SelectionKeyDown") return DrawBundleSelectionState::SelectionKeyDown;
                if (value == "Selected") return DrawBundleSelectionState::Selected;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "nointeraction") return DrawBundleSelectionState::NoInteraction;
                if (valueLower == "hover") return DrawBundleSelectionState::Hover;
                if (valueLower == "selectionkeydown") return DrawBundleSelectionState::SelectionKeyDown;
                if (valueLower == "selected") return DrawBundleSelectionState::Selected;
            }
            
            return DrawBundleSelectionState::NoInteraction;
        }

        /// <summary>
        /// Test to see whether value has the given flag.
        /// </summary>
        /// <param name="origin">Origin to look for flag in. </param>
        /// <param name="lookFor">Value to look for. </param>
        /// <returns>True means has flag. </returns>
        static bool HasFlag(DrawBundleSelectionState origin, DrawBundleSelectionState lookFor)
        {
            return (origin & lookFor) != DrawBundleSelectionState::NoInteraction;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
