#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace SuperGameTools
{
    /// <summary>
    /// Describes the selection state of the given draw bundle so that it maybe rendered correctly.
    /// </summary>
    enum class DrawBundleSelectionState : uint8_t
    {
        /// <summary>
        /// No cursor is interacting and the object for this bundle is not selected.
        /// </summary>
        NoInteraction = 0,

        /// <summary>
        /// The bundle has either a mouse cursor or other method to demostrate it could be selected on a key press.
        /// </summary>
        Hover = 1 << 0,

        /// <summary>
        /// The selection key is down over the object.
        /// </summary>
        SelectionKeyDown = 1 << 1,

        /// <summary>
        /// The object for the bundle is currently selected.
        /// </summary>
        Selected = 1 << 2,
    };

    inline DrawBundleSelectionState operator | (DrawBundleSelectionState lhs, DrawBundleSelectionState rhs)
    {
        using T = std::underlying_type_t <DrawBundleSelectionState>;
        return static_cast<DrawBundleSelectionState>(static_cast<T>(lhs) | static_cast<T>(rhs));
    }

    inline DrawBundleSelectionState& operator |= (DrawBundleSelectionState& lhs, DrawBundleSelectionState rhs)
    {
        lhs = lhs | rhs;
        return lhs;
    }

    inline DrawBundleSelectionState operator & (DrawBundleSelectionState lhs, DrawBundleSelectionState rhs)
    {
        using T = std::underlying_type_t <DrawBundleSelectionState>;
        return static_cast<DrawBundleSelectionState>(static_cast<T>(lhs) & static_cast<T>(rhs));
    }

    inline DrawBundleSelectionState& operator &= (DrawBundleSelectionState& lhs, DrawBundleSelectionState rhs)
    {
        lhs = lhs & rhs;
        return lhs;
    }

    inline DrawBundleSelectionState operator ^ (DrawBundleSelectionState lhs, DrawBundleSelectionState rhs)
    {
        using T = std::underlying_type_t <DrawBundleSelectionState>;
        return static_cast<DrawBundleSelectionState>(static_cast<T>(lhs) ^ static_cast<T>(rhs));
    }

    inline DrawBundleSelectionState& operator ^= (DrawBundleSelectionState& lhs, DrawBundleSelectionState rhs)
    {
        lhs = lhs ^ rhs;
        return lhs;
    }

    inline DrawBundleSelectionState operator ~ (DrawBundleSelectionState lhs)
    {
        using T = std::underlying_type_t <DrawBundleSelectionState>;
        return static_cast<DrawBundleSelectionState>(~static_cast<T>(lhs));
    }


    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EDrawBundleSelectionState
    {
    public:
        static DrawBundleSelectionState Min() { return DrawBundleSelectionState::NoInteraction; }
        static DrawBundleSelectionState Max() { return DrawBundleSelectionState::Selected; }

        static DrawBundleSelectionState* ToArray()
        {
            static DrawBundleSelectionState returnArray[] =
            {
                DrawBundleSelectionState::NoInteraction,
                DrawBundleSelectionState::Hover,
                DrawBundleSelectionState::SelectionKeyDown,
                DrawBundleSelectionState::Selected,
            };
            
            return returnArray;
        }

        static std::vector<DrawBundleSelectionState> ToVector()
        {
            static std::vector<DrawBundleSelectionState> returnVector =
            {
                DrawBundleSelectionState::NoInteraction,
                DrawBundleSelectionState::Hover,
                DrawBundleSelectionState::SelectionKeyDown,
                DrawBundleSelectionState::Selected,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "NoInteraction",
                "Hover",
                "SelectionKeyDown",
                "Selected",
            };
            
            return returnVector;
        }

        static std::string ToString(DrawBundleSelectionState value)
        {
            if(value == DrawBundleSelectionState::NoInteraction)
            {
                return "NoInteraction";
            }
            
            std::vector<std::string> entries;
            if(HasFlag(value,DrawBundleSelectionState::NoInteraction))
            {
                entries.emplace_back("NoInteraction");
            }
            if(HasFlag(value,DrawBundleSelectionState::Hover))
            {
                entries.emplace_back("Hover");
            }
            if(HasFlag(value,DrawBundleSelectionState::SelectionKeyDown))
            {
                entries.emplace_back("SelectionKeyDown");
            }
            if(HasFlag(value,DrawBundleSelectionState::Selected))
            {
                entries.emplace_back("Selected");
            }
            
            std::string returnToString = {};
            for (const std::string& entry : entries)
            {
                if (returnToString.empty())
                {
                    returnToString = entry;
                }
                else
                {
                    returnToString += " | " + entry;
                }
            }
            return returnToString;
        }

        static DrawBundleSelectionState FromString(const std::string& value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "NoInteraction") return DrawBundleSelectionState::NoInteraction;
                if (value == "Hover") return DrawBundleSelectionState::Hover;
                if (value == "SelectionKeyDown") return DrawBundleSelectionState::SelectionKeyDown;
                if (value == "Selected") return DrawBundleSelectionState::Selected;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "nointeraction") return DrawBundleSelectionState::NoInteraction;
                if (valueLower == "hover") return DrawBundleSelectionState::Hover;
                if (valueLower == "selectionkeydown") return DrawBundleSelectionState::SelectionKeyDown;
                if (valueLower == "selected") return DrawBundleSelectionState::Selected;
            }
            
            return DrawBundleSelectionState::NoInteraction;
        }

        /// <summary>
        /// Test to see whether value has the given flag.
        /// </summary>
        /// <param name="origin">Origin to look for flag in. </param>
        /// <param name="lookFor">Value to look for. </param>
        /// <returns>True means has flag. </returns>
        static bool HasFlag(DrawBundleSelectionState origin, DrawBundleSelectionState lookFor)
        {
            return (origin & lookFor) != DrawBundleSelectionState::NoInteraction;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
