#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace FatedQuestLibraries
{
    /// <summary>
    /// Describes how to display text using basic styles from markdown.
    /// </summary>
    enum class MarkdownTextStyle : uint8_t
    {
        Plain = 0,

        Bold = 1 << 0,

        Italic = 1 << 1,

        Strike = 1 << 2,

        Highlight = 1 << 3,

        InlineCode = 1 << 4,

        Underline = 1 << 5,
    };

    inline MarkdownTextStyle operator | (MarkdownTextStyle lhs, MarkdownTextStyle rhs)
    {
        using T = std::underlying_type_t <MarkdownTextStyle>;
        return static_cast<MarkdownTextStyle>(static_cast<T>(lhs) | static_cast<T>(rhs));
    }

    inline MarkdownTextStyle& operator |= (MarkdownTextStyle& lhs, MarkdownTextStyle rhs)
    {
        lhs = lhs | rhs;
        return lhs;
    }

    inline MarkdownTextStyle operator & (MarkdownTextStyle lhs, MarkdownTextStyle rhs)
    {
        using T = std::underlying_type_t <MarkdownTextStyle>;
        return static_cast<MarkdownTextStyle>(static_cast<T>(lhs) & static_cast<T>(rhs));
    }

    inline MarkdownTextStyle& operator &= (MarkdownTextStyle& lhs, MarkdownTextStyle rhs)
    {
        lhs = lhs | rhs;
        return lhs;
    }

    inline MarkdownTextStyle operator ^ (MarkdownTextStyle lhs, MarkdownTextStyle rhs)
    {
        using T = std::underlying_type_t <MarkdownTextStyle>;
        return static_cast<MarkdownTextStyle>(static_cast<T>(lhs) ^ static_cast<T>(rhs));
    }

    inline MarkdownTextStyle& operator ^= (MarkdownTextStyle& lhs, MarkdownTextStyle rhs)
    {
        lhs = lhs ^ rhs;
        return lhs;
    }

    inline MarkdownTextStyle operator ~ (MarkdownTextStyle lhs)
    {
        using T = std::underlying_type_t <MarkdownTextStyle>;
        return static_cast<MarkdownTextStyle>(~static_cast<T>(lhs));
    }

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EMarkdownTextStyle
    {
    public:
        static MarkdownTextStyle Min() { return MarkdownTextStyle::Plain; }
        static MarkdownTextStyle Max() { return MarkdownTextStyle::Underline; }

        static MarkdownTextStyle* ToArray()
        {
            static MarkdownTextStyle returnArray[] =
            {
                MarkdownTextStyle::Plain,
                MarkdownTextStyle::Bold,
                MarkdownTextStyle::Italic,
                MarkdownTextStyle::Strike,
                MarkdownTextStyle::Highlight,
                MarkdownTextStyle::InlineCode,
                MarkdownTextStyle::Underline,
            };
            
            return returnArray;
        }

        static std::vector<MarkdownTextStyle> ToVector()
        {
            static std::vector<MarkdownTextStyle> returnVector =
            {
                MarkdownTextStyle::Plain,
                MarkdownTextStyle::Bold,
                MarkdownTextStyle::Italic,
                MarkdownTextStyle::Strike,
                MarkdownTextStyle::Highlight,
                MarkdownTextStyle::InlineCode,
                MarkdownTextStyle::Underline,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "Plain",
                "Bold",
                "Italic",
                "Strike",
                "Highlight",
                "InlineCode",
                "Underline",
            };
            
            return returnVector;
        }

        static std::string ToString(MarkdownTextStyle value)
        {
            if(value == MarkdownTextStyle::Plain)
            {
                return "Plain";
            }
            
            std::vector<std::string> entries;
            if(HasFlag(value,MarkdownTextStyle::Plain))
            {
                entries.emplace_back("Plain");
            }
            if(HasFlag(value,MarkdownTextStyle::Bold))
            {
                entries.emplace_back("Bold");
            }
            if(HasFlag(value,MarkdownTextStyle::Italic))
            {
                entries.emplace_back("Italic");
            }
            if(HasFlag(value,MarkdownTextStyle::Strike))
            {
                entries.emplace_back("Strike");
            }
            if(HasFlag(value,MarkdownTextStyle::Highlight))
            {
                entries.emplace_back("Highlight");
            }
            if(HasFlag(value,MarkdownTextStyle::InlineCode))
            {
                entries.emplace_back("InlineCode");
            }
            if(HasFlag(value,MarkdownTextStyle::Underline))
            {
                entries.emplace_back("Underline");
            }
            
            std::string returnToString = {};
            for (const std::string& entry : entries)
            {
                if (returnToString.empty())
                {
                    returnToString = entry;
                }
                else
                {
                    returnToString += " | " + entry;
                }
            }
            return returnToString;
        }

        static MarkdownTextStyle FromString(std::string value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "Plain") return MarkdownTextStyle::Plain;
                if (value == "Bold") return MarkdownTextStyle::Bold;
                if (value == "Italic") return MarkdownTextStyle::Italic;
                if (value == "Strike") return MarkdownTextStyle::Strike;
                if (value == "Highlight") return MarkdownTextStyle::Highlight;
                if (value == "InlineCode") return MarkdownTextStyle::InlineCode;
                if (value == "Underline") return MarkdownTextStyle::Underline;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "plain") return MarkdownTextStyle::Plain;
                if (valueLower == "bold") return MarkdownTextStyle::Bold;
                if (valueLower == "italic") return MarkdownTextStyle::Italic;
                if (valueLower == "strike") return MarkdownTextStyle::Strike;
                if (valueLower == "highlight") return MarkdownTextStyle::Highlight;
                if (valueLower == "inlinecode") return MarkdownTextStyle::InlineCode;
                if (valueLower == "underline") return MarkdownTextStyle::Underline;
            }
            
            return MarkdownTextStyle::Plain;
        }

        /// <summary>
        /// Test to see whether value has the given flag.
        /// </summary>
        /// <param name="origin">Origin to look for flag in. </param>
        /// <param name="lookFor">Value to look for. </param>
        /// <returns>True means has flag. </returns>
        static bool HasFlag(MarkdownTextStyle origin, MarkdownTextStyle lookFor)
        {
            return (origin & lookFor) != MarkdownTextStyle::Plain;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
