#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace FatedQuestLibraries
{
    /// <summary>
    /// Describes whether the text segement has a special behaviour applied to it outside of styling.
    /// </summary>
    enum class MarkdownTextStyleSpecialAttribute : uint8_t
    {
        /// <summary>
        /// Just styling.
        /// </summary>
        None,

        /// <summary>
        /// Hyperlink to a location.
        /// </summary>
        Link,

        /// <summary>
        /// An inline image.
        /// </summary>
        Image,
    };

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EMarkdownTextStyleSpecialAttribute
    {
    public:
        static MarkdownTextStyleSpecialAttribute Min() { return MarkdownTextStyleSpecialAttribute::None; }
        static MarkdownTextStyleSpecialAttribute Max() { return MarkdownTextStyleSpecialAttribute::Image; }

        static MarkdownTextStyleSpecialAttribute* ToArray()
        {
            static MarkdownTextStyleSpecialAttribute returnArray[] =
            {
                MarkdownTextStyleSpecialAttribute::None,
                MarkdownTextStyleSpecialAttribute::Link,
                MarkdownTextStyleSpecialAttribute::Image,
            };
            
            return returnArray;
        }

        static std::vector<MarkdownTextStyleSpecialAttribute> ToVector()
        {
            static std::vector<MarkdownTextStyleSpecialAttribute> returnVector =
            {
                MarkdownTextStyleSpecialAttribute::None,
                MarkdownTextStyleSpecialAttribute::Link,
                MarkdownTextStyleSpecialAttribute::Image,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "None",
                "Link",
                "Image",
            };
            
            return returnVector;
        }

        static std::string ToString(MarkdownTextStyleSpecialAttribute value)
        {
            switch (value)
            {
                case MarkdownTextStyleSpecialAttribute::None: return "None";
                case MarkdownTextStyleSpecialAttribute::Link: return "Link";
                case MarkdownTextStyleSpecialAttribute::Image: return "Image";
            }
            
            return "None";
        }

        static MarkdownTextStyleSpecialAttribute FromString(std::string value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "None") return MarkdownTextStyleSpecialAttribute::None;
                if (value == "Link") return MarkdownTextStyleSpecialAttribute::Link;
                if (value == "Image") return MarkdownTextStyleSpecialAttribute::Image;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "none") return MarkdownTextStyleSpecialAttribute::None;
                if (valueLower == "link") return MarkdownTextStyleSpecialAttribute::Link;
                if (valueLower == "image") return MarkdownTextStyleSpecialAttribute::Image;
            }
            
            return MarkdownTextStyleSpecialAttribute::None;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
