#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace SuperGameTools
{
    /// <summary>
    /// The method used to create a brand new universal object data file.
    /// </summary>
    enum class UniversalObjectDataTemplateCreationMethod : uint8_t
    {
        /// <summary>
        /// Only used for unsuccessful parsing.
        /// </summary>
        Unknown = 0,

        /// <summary>
        /// Takes the child elements and simply uses a string replace to make it specific.
        /// </summary>
        Simple,
    };

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EUniversalObjectDataTemplateCreationMethod
    {
    public:
        static UniversalObjectDataTemplateCreationMethod Min() { return UniversalObjectDataTemplateCreationMethod::Simple; }
        static UniversalObjectDataTemplateCreationMethod Max() { return UniversalObjectDataTemplateCreationMethod::Simple; }

        static UniversalObjectDataTemplateCreationMethod* ToArray()
        {
            static UniversalObjectDataTemplateCreationMethod returnArray[] =
            {
                UniversalObjectDataTemplateCreationMethod::Simple,
            };
            
            return returnArray;
        }

        static std::vector<UniversalObjectDataTemplateCreationMethod> ToVector()
        {
            static std::vector<UniversalObjectDataTemplateCreationMethod> returnVector =
            {
                UniversalObjectDataTemplateCreationMethod::Simple,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "Simple",
            };
            
            return returnVector;
        }

        static std::string ToString(UniversalObjectDataTemplateCreationMethod value)
        {
            switch (value)
            {
                case UniversalObjectDataTemplateCreationMethod::Unknown: return "Unknown";
                case UniversalObjectDataTemplateCreationMethod::Simple: return "Simple";
            }
            
            return "Unknown";
        }

        static UniversalObjectDataTemplateCreationMethod FromString(std::string value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "Unknown") return UniversalObjectDataTemplateCreationMethod::Unknown;
                if (value == "Simple") return UniversalObjectDataTemplateCreationMethod::Simple;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "unknown") return UniversalObjectDataTemplateCreationMethod::Unknown;
                if (valueLower == "simple") return UniversalObjectDataTemplateCreationMethod::Simple;
            }
            
            return UniversalObjectDataTemplateCreationMethod::Unknown;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
