#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace SuperGameTools
{
    /// <summary>
    /// Describes interactions to the Asset Tiles rendered via the Asset Browser.
    /// </summary>
    enum class AssetTileInteractionRawState : uint8_t
    {
        /// <summary>
        /// No hover or interaction.
        /// </summary>
        NoInteraction = 0,

        /// <summary>
        /// Tile is hovered or should be rendered as such.
        /// If this is not paired with an action assume only hover has occured.
        /// </summary>
        Hover = 1 << 0,

        /// <summary>
        /// Left click is currently down.
        /// </summary>
        LeftClickDown = 1 << 1,

        /// <summary>
        /// Left click was down and now has been released.
        /// </summary>
        LeftClickReleased = 1 << 2,
    };

    /// <summary>
    /// Combines flags. For example: auto var = left | right; returns a bitflag containing both left and right. 
    /// </summary>
    inline AssetTileInteractionRawState operator | (AssetTileInteractionRawState lhs, AssetTileInteractionRawState rhs)
    {
        using T = std::underlying_type_t <AssetTileInteractionRawState>;
        return static_cast<AssetTileInteractionRawState>(static_cast<T>(lhs) | static_cast<T>(rhs));
    }

    /// <summary>
    /// Combines flags in assignment. For example: left |= right; Adds right flag to left variable. 
    /// </summary>
    inline AssetTileInteractionRawState& operator |= (AssetTileInteractionRawState& lhs, AssetTileInteractionRawState rhs)
    {
        lhs = lhs | rhs;
        return lhs;
    }

    /// <summary>
    /// Gets the intersection of flags. Mostly used as in this example: bool isSet = ((state & flag1) == flag1); 
    /// Is set would be true if state has the flag. Also this can be combined with ~ to remove a flag (see below). 
    /// HasFlag will also do this for you in nicer syntax. 
    /// </summary>
    inline AssetTileInteractionRawState operator & (AssetTileInteractionRawState lhs, AssetTileInteractionRawState rhs)
    {
        using T = std::underlying_type_t <AssetTileInteractionRawState>;
        return static_cast<AssetTileInteractionRawState>(static_cast<T>(lhs) & static_cast<T>(rhs));
    }

    /// <summary>
    /// Returns the intersection of the flags in an assignment. 
    /// Mostly combined with ~ as in this example: state &= ~flagToRemove; 
    /// This would remove flagToRemove from the given state. 
    /// </summary>
    inline AssetTileInteractionRawState& operator &= (AssetTileInteractionRawState& lhs, AssetTileInteractionRawState rhs)
    {
        lhs = lhs & rhs;
        return lhs;
    }

    /// <summary>
    /// Performs an XOR operation on the left and right and returns the result. 
    /// This is mostly which to compare two sets of flags and to figure out where they differ. 
    /// left = flag1; right = flag1 | flag2; different = left ^ right; 
    /// different in this example will be flag2.
    /// Keep in mind you would not know where the differences are you would need to do this: 
    /// bool checkLeft = different & left; - nothing removed / added. 
    /// bool checkRight = different & right; - flag2 added. 
    /// </summary>
    inline AssetTileInteractionRawState operator ^ (AssetTileInteractionRawState lhs, AssetTileInteractionRawState rhs)
    {
        using T = std::underlying_type_t <AssetTileInteractionRawState>;
        return static_cast<AssetTileInteractionRawState>(static_cast<T>(lhs) ^ static_cast<T>(rhs));
    }

    /// <summary>
    /// Performs an XOR operation on the flag which results in a toggle assignment.
    /// Example: state ^= flag1; This would toggle whether flag1 is on within the enum.
    /// </summary>
    inline AssetTileInteractionRawState& operator ^= (AssetTileInteractionRawState& lhs, AssetTileInteractionRawState rhs)
    {
        lhs = lhs ^ rhs;
        return lhs;
    }

    /// <summary>
    /// Returns the opposite or 'unset' or 'invert' flag of the given. 
    /// Mostly combined with &= as in this example: state &= ~flagToRemove; 
    /// This would remove flagToRemove from the given state. 
    /// </summary>
    inline AssetTileInteractionRawState operator ~ (AssetTileInteractionRawState lhs)
    {
        using T = std::underlying_type_t <AssetTileInteractionRawState>;
        return static_cast<AssetTileInteractionRawState>(~static_cast<T>(lhs));
    }

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EAssetTileInteractionRawState
    {
    public:
        static AssetTileInteractionRawState Min() { return AssetTileInteractionRawState::NoInteraction; }
        static AssetTileInteractionRawState Max() { return AssetTileInteractionRawState::LeftClickReleased; }

        static AssetTileInteractionRawState* ToArray()
        {
            static AssetTileInteractionRawState returnArray[] =
            {
                AssetTileInteractionRawState::NoInteraction,
                AssetTileInteractionRawState::Hover,
                AssetTileInteractionRawState::LeftClickDown,
                AssetTileInteractionRawState::LeftClickReleased,
            };
            
            return returnArray;
        }

        static std::vector<AssetTileInteractionRawState> ToVector()
        {
            static std::vector<AssetTileInteractionRawState> returnVector =
            {
                AssetTileInteractionRawState::NoInteraction,
                AssetTileInteractionRawState::Hover,
                AssetTileInteractionRawState::LeftClickDown,
                AssetTileInteractionRawState::LeftClickReleased,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "NoInteraction",
                "Hover",
                "LeftClickDown",
                "LeftClickReleased",
            };
            
            return returnVector;
        }

        static std::string ToString(AssetTileInteractionRawState value)
        {
            if(value == AssetTileInteractionRawState::NoInteraction)
            {
                return "NoInteraction";
            }
            
            std::vector<std::string> entries;
            if(HasFlag(value,AssetTileInteractionRawState::NoInteraction))
            {
                entries.emplace_back("NoInteraction");
            }
            if(HasFlag(value,AssetTileInteractionRawState::Hover))
            {
                entries.emplace_back("Hover");
            }
            if(HasFlag(value,AssetTileInteractionRawState::LeftClickDown))
            {
                entries.emplace_back("LeftClickDown");
            }
            if(HasFlag(value,AssetTileInteractionRawState::LeftClickReleased))
            {
                entries.emplace_back("LeftClickReleased");
            }
            
            std::string returnToString = {};
            for (const std::string& entry : entries)
            {
                if (returnToString.empty())
                {
                    returnToString = entry;
                }
                else
                {
                    returnToString += " | " + entry;
                }
            }
            return returnToString;
        }

        static AssetTileInteractionRawState FromString(const std::string& value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "NoInteraction") return AssetTileInteractionRawState::NoInteraction;
                if (value == "Hover") return AssetTileInteractionRawState::Hover;
                if (value == "LeftClickDown") return AssetTileInteractionRawState::LeftClickDown;
                if (value == "LeftClickReleased") return AssetTileInteractionRawState::LeftClickReleased;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "nointeraction") return AssetTileInteractionRawState::NoInteraction;
                if (valueLower == "hover") return AssetTileInteractionRawState::Hover;
                if (valueLower == "leftclickdown") return AssetTileInteractionRawState::LeftClickDown;
                if (valueLower == "leftclickreleased") return AssetTileInteractionRawState::LeftClickReleased;
            }
            
            return AssetTileInteractionRawState::NoInteraction;
        }

        /// <summary>
        /// Test to see whether value has the given flag.
        /// </summary>
        /// <param name="origin">Origin to look for flag in. </param>
        /// <param name="lookFor">Value to look for. </param>
        /// <returns>True means has flag. </returns>
        static bool HasFlag(AssetTileInteractionRawState origin, AssetTileInteractionRawState lookFor)
        {
            return (origin & lookFor) != AssetTileInteractionRawState::NoInteraction;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
