#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace SuperGameEngine
{
    /// <summary>
    /// Describes a set of predefined locations for window spawning or movement.
    /// </summary>
    enum class WindowPredefinedPosition : uint8_t
    {
        /// <summary>
        /// Only used for unsuccessful parsing.
        /// </summary>
        Unknown = 0,

        /// <summary>
        /// Centers the window on the screen it was opened on  (at least in windows)
        /// </summary>
        Centered,
    };

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EWindowPredefinedPosition
    {
    public:
        static WindowPredefinedPosition Min() { return WindowPredefinedPosition::Centered; }
        static WindowPredefinedPosition Max() { return WindowPredefinedPosition::Centered; }

        static WindowPredefinedPosition* ToArray()
        {
            static WindowPredefinedPosition returnArray[] =
            {
                WindowPredefinedPosition::Centered,
            };
            
            return returnArray;
        }

        static std::vector<WindowPredefinedPosition> ToVector()
        {
            static std::vector<WindowPredefinedPosition> returnVector =
            {
                WindowPredefinedPosition::Centered,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "Centered",
            };
            
            return returnVector;
        }

        static std::string* ToArrayValues()
        {
            static std::string returnArray[] =
            {
                "Centered",
            };
            
            return returnArray;
        }

        static std::string ToString(WindowPredefinedPosition value)
        {
            switch (value)
            {
                case WindowPredefinedPosition::Unknown: return "Unknown";
                case WindowPredefinedPosition::Centered: return "Centered";
            }
            
            return "Unknown";
        }

        static WindowPredefinedPosition FromString(const std::string& value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "Unknown") return WindowPredefinedPosition::Unknown;
                if (value == "Centered") return WindowPredefinedPosition::Centered;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "unknown") return WindowPredefinedPosition::Unknown;
                if (valueLower == "centered") return WindowPredefinedPosition::Centered;
            }
            
            return WindowPredefinedPosition::Unknown;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
