#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace SuperGameTools
{
    /// <summary>
    /// A list of fonts included in the package.
    /// </summary>
    enum class EmbeddedFont : int8_t
    {
        /// <summary>
        /// Only used for unsuccessful parsing.
        /// </summary>
        Unknown = -1,

        /// <summary>
        /// Sans Google Font.
        /// </summary>
        NotoSansVariableFont,
    };

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EEmbeddedFont
    {
    public:
        static EmbeddedFont Min() { return EmbeddedFont::NotoSansVariableFont; }
        static EmbeddedFont Max() { return EmbeddedFont::NotoSansVariableFont; }

        static EmbeddedFont* ToArray()
        {
            static EmbeddedFont returnArray[] =
            {
                EmbeddedFont::NotoSansVariableFont,
            };
            
            return returnArray;
        }

        static std::vector<EmbeddedFont> ToVector()
        {
            static std::vector<EmbeddedFont> returnVector =
            {
                EmbeddedFont::NotoSansVariableFont,
            };
            
            return returnVector;
        }

        static std::string ToString(EmbeddedFont value)
        {
            switch (value)
            {
                case EmbeddedFont::Unknown: return "Unknown";
                case EmbeddedFont::NotoSansVariableFont: return "NotoSansVariableFont";
            }
            
            return "Unknown";
        }

        static EmbeddedFont FromString(std::string value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "Unknown") return EmbeddedFont::Unknown;
                if (value == "NotoSansVariableFont") return EmbeddedFont::NotoSansVariableFont;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "unknown") return EmbeddedFont::Unknown;
                if (valueLower == "notosansvariablefont") return EmbeddedFont::NotoSansVariableFont;
            }
            
            return EmbeddedFont::Unknown;
        }

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
