#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace SuperGameInput
{
    /// <summary>
    /// Describes the state of keys pressed on a keyboard,
    /// mouse buttons or controller buttons.
    /// </summary>
    enum class KeyOrButtonState : uint8_t
    {
        /// <summary>
        /// Only used for unsuccessful parsing.
        /// </summary>
        Unknown = 0,

        /// <summary>
        /// Key is not pressed at all.
        /// Default state.
        /// </summary>
        Unpressed = 1 << 0,

        /// <summary>
        /// Has just been pressed. Always also means down. Fires first frame.
        /// </summary>
        Pressed = 1 << 1,

        /// <summary>
        /// Key is down. Fires every frame.
        /// </summary>
        Down = 1 << 2,

        /// <summary>
        /// Key was just release. Fires first frame.
        /// </summary>
        Up = 1 << 3,
    };

    /// <summary>
    /// Combines flags. For example: auto var = left | right; returns a bitflag containing both left and right. 
    /// </summary>
    inline KeyOrButtonState operator | (KeyOrButtonState lhs, KeyOrButtonState rhs)
    {
        using T = std::underlying_type_t <KeyOrButtonState>;
        return static_cast<KeyOrButtonState>(static_cast<T>(lhs) | static_cast<T>(rhs));
    }

    /// <summary>
    /// Combines flags in assignment. For example: left |= right; Adds right flag to left variable. 
    /// </summary>
    inline KeyOrButtonState& operator |= (KeyOrButtonState& lhs, KeyOrButtonState rhs)
    {
        lhs = lhs | rhs;
        return lhs;
    }

    /// <summary>
    /// Gets the intersection of flags. Mostly used as in this example: bool isSet = ((state & flag1) == flag1); 
    /// Is set would be true if state has the flag. Also this can be combined with ~ to remove a flag (see below). 
    /// HasFlag will also do this for you in nicer syntax. 
    /// </summary>
    inline KeyOrButtonState operator & (KeyOrButtonState lhs, KeyOrButtonState rhs)
    {
        using T = std::underlying_type_t <KeyOrButtonState>;
        return static_cast<KeyOrButtonState>(static_cast<T>(lhs) & static_cast<T>(rhs));
    }

    /// <summary>
    /// Returns the intersection of the flags in an assignment. 
    /// Mostly combined with ~ as in this example: state &= ~flagToRemove; 
    /// This would remove flagToRemove from the given state. 
    /// </summary>
    inline KeyOrButtonState& operator &= (KeyOrButtonState& lhs, KeyOrButtonState rhs)
    {
        lhs = lhs & rhs;
        return lhs;
    }

    /// <summary>
    /// Performs an XOR operation on the left and right and returns the result. 
    /// This is mostly which to compare two sets of flags and to figure out where they differ. 
    /// left = flag1; right = flag1 | flag2; different = left ^ right; 
    /// different in this example will be flag2.
    /// Keep in mind you would not know where the differences are you would need to do this: 
    /// bool checkLeft = different & left; - nothing removed / added. 
    /// bool checkRight = different & right; - flag2 added. 
    /// </summary>
    inline KeyOrButtonState operator ^ (KeyOrButtonState lhs, KeyOrButtonState rhs)
    {
        using T = std::underlying_type_t <KeyOrButtonState>;
        return static_cast<KeyOrButtonState>(static_cast<T>(lhs) ^ static_cast<T>(rhs));
    }

    /// <summary>
    /// Performs an XOR operation on the flag which results in a toggle assignment.
    /// Example: state ^= flag1; This would toggle whether flag1 is on within the enum.
    /// </summary>
    inline KeyOrButtonState& operator ^= (KeyOrButtonState& lhs, KeyOrButtonState rhs)
    {
        lhs = lhs ^ rhs;
        return lhs;
    }

    /// <summary>
    /// Returns the opposite or 'unset' or 'invert' flag of the given. 
    /// Mostly combined with &= as in this example: state &= ~flagToRemove; 
    /// This would remove flagToRemove from the given state. 
    /// </summary>
    inline KeyOrButtonState operator ~ (KeyOrButtonState lhs)
    {
        using T = std::underlying_type_t <KeyOrButtonState>;
        return static_cast<KeyOrButtonState>(~static_cast<T>(lhs));
    }

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EKeyOrButtonState
    {
    public:
        static KeyOrButtonState Min() { return KeyOrButtonState::Unpressed; }
        static KeyOrButtonState Max() { return KeyOrButtonState::Up; }

        static KeyOrButtonState* ToArray()
        {
            static KeyOrButtonState returnArray[] =
            {
                KeyOrButtonState::Unpressed,
                KeyOrButtonState::Pressed,
                KeyOrButtonState::Down,
                KeyOrButtonState::Up,
            };
            
            return returnArray;
        }

        static std::vector<KeyOrButtonState> ToVector()
        {
            static std::vector<KeyOrButtonState> returnVector =
            {
                KeyOrButtonState::Unpressed,
                KeyOrButtonState::Pressed,
                KeyOrButtonState::Down,
                KeyOrButtonState::Up,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "Unpressed",
                "Pressed",
                "Down",
                "Up",
            };
            
            return returnVector;
        }

        static std::string* ToArrayValues()
        {
            static std::string returnArray[] =
            {
                "Unpressed",
                "Pressed",
                "Down",
                "Up",
            };
            
            return returnArray;
        }

        static std::string ToString(KeyOrButtonState value)
        {
            if(value == KeyOrButtonState::Unpressed)
            {
                return "Unpressed";
            }
            
            std::vector<std::string> entries;
            if(HasFlag(value,KeyOrButtonState::Unknown))
            {
                entries.emplace_back("Unknown");
            }
            if(HasFlag(value,KeyOrButtonState::Unpressed))
            {
                entries.emplace_back("Unpressed");
            }
            if(HasFlag(value,KeyOrButtonState::Pressed))
            {
                entries.emplace_back("Pressed");
            }
            if(HasFlag(value,KeyOrButtonState::Down))
            {
                entries.emplace_back("Down");
            }
            if(HasFlag(value,KeyOrButtonState::Up))
            {
                entries.emplace_back("Up");
            }
            
            std::string returnToString = {};
            for (const std::string& entry : entries)
            {
                if (returnToString.empty())
                {
                    returnToString = entry;
                }
                else
                {
                    returnToString += " | " + entry;
                }
            }
            return returnToString;
        }

        static KeyOrButtonState FromString(const std::string& value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "Unknown") return KeyOrButtonState::Unknown;
                if (value == "Unpressed") return KeyOrButtonState::Unpressed;
                if (value == "Pressed") return KeyOrButtonState::Pressed;
                if (value == "Down") return KeyOrButtonState::Down;
                if (value == "Up") return KeyOrButtonState::Up;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "unknown") return KeyOrButtonState::Unknown;
                if (valueLower == "unpressed") return KeyOrButtonState::Unpressed;
                if (valueLower == "pressed") return KeyOrButtonState::Pressed;
                if (valueLower == "down") return KeyOrButtonState::Down;
                if (valueLower == "up") return KeyOrButtonState::Up;
            }
            
            return KeyOrButtonState::Unknown;
        }

        /// <summary>
        /// Test to see whether value has the given flag.
        /// </summary>
        /// <param name="origin">Origin to look for flag in. </param>
        /// <param name="lookFor">Value to look for. </param>
        /// <returns>True means has flag. </returns>
        static bool HasFlag(KeyOrButtonState origin, KeyOrButtonState lookFor)
        {
            return (origin & lookFor) != KeyOrButtonState::Unknown;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
