#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace SuperGameEngine
{
    /// <summary>
    /// Defines how to flip a given texture.
    /// </summary>
    enum class TextureOrientation : uint8_t
    {
        /// <summary>
        /// Only used for unsuccessful parsing.
        /// </summary>
        Unknown = 0,

        /// <summary>
        /// Do not flip.
        /// </summary>
        None,

        Horizontally,

        Vertically,
    };

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class ETextureOrientation
    {
    public:
        static TextureOrientation Min() { return TextureOrientation::None; }
        static TextureOrientation Max() { return TextureOrientation::Vertically; }

        static TextureOrientation* ToArray()
        {
            static TextureOrientation returnArray[] =
            {
                TextureOrientation::None,
                TextureOrientation::Horizontally,
                TextureOrientation::Vertically,
            };
            
            return returnArray;
        }

        static std::vector<TextureOrientation> ToVector()
        {
            static std::vector<TextureOrientation> returnVector =
            {
                TextureOrientation::None,
                TextureOrientation::Horizontally,
                TextureOrientation::Vertically,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "None",
                "Horizontally",
                "Vertically",
            };
            
            return returnVector;
        }

        static std::string* ToArrayValues()
        {
            static std::string returnArray[] =
            {
                "None",
                "Horizontally",
                "Vertically",
            };
            
            return returnArray;
        }

        static std::string ToString(TextureOrientation value)
        {
            switch (value)
            {
                case TextureOrientation::Unknown: return "Unknown";
                case TextureOrientation::None: return "None";
                case TextureOrientation::Horizontally: return "Horizontally";
                case TextureOrientation::Vertically: return "Vertically";
            }
            
            return "Unknown";
        }

        static TextureOrientation FromString(const std::string& value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "Unknown") return TextureOrientation::Unknown;
                if (value == "None") return TextureOrientation::None;
                if (value == "Horizontally") return TextureOrientation::Horizontally;
                if (value == "Vertically") return TextureOrientation::Vertically;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "unknown") return TextureOrientation::Unknown;
                if (valueLower == "none") return TextureOrientation::None;
                if (valueLower == "horizontally") return TextureOrientation::Horizontally;
                if (valueLower == "vertically") return TextureOrientation::Vertically;
            }
            
            return TextureOrientation::Unknown;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
