#pragma once
// +------------------------------+
// Generated by EnumGenerator as an
// SuperEnum. See Tools for details.
// Date: 2024/11/27 20:43:39
// +------------------------------+
namespace SuperGameEngine
{
    enum class ControllerComparisonType
    {
        Entry,
        EntryTwo,
        EntryThree,
    }
}
