#pragma once
// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// Date: 2024/11/28 21:1:4
// +------------------------------+
namespace SuperGameEngine
{
    /// <summary>
    /// How to compare values with inputs.
    /// </summary>
    enum class ControllerComparisonType
    {
        /// <summary>
        /// Only used for unsuccessful parsing.
        /// </summary>
        Unknown,

        Greater,

        Less,

        Equals,
    }
}
