#pragma once

// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// Date: 2024/11/30 14:19:46
// +------------------------------+
namespace SuperGameEngine
{
    /// <summary>
    /// How to compare values with inputs.
    /// </summary>
    enum class ControllerComparisonType
    {
        /// <summary>
        /// Only used for unsuccessful parsing.
        /// </summary>
        Unknown = -1,

        Greater,

        Less,

        Equals,
    };

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EControllerComparisonType : public Object
    {
    public:
        static ControllerComparisonType Min() { return ControllerComparisonType::Greater; }
        static ControllerComparisonType Max() { return ControllerComparisonType::Equals; }

        static ControllerComparisonType* ToArray()
        {
            static ControllerComparisonType returnArray[] =
            {
                ControllerComparisonType::Greater,
                ControllerComparisonType::Less,
                ControllerComparisonType::Equals,
            };
            
            return returnArray;
        }

        static std::vector<ControllerComparisonType> ToVector()
        {
            static std::vector<ControllerComparisonType> returnVector =
            {
                ControllerComparisonType::Greater,
                ControllerComparisonType::Less,
                ControllerComparisonType::Equals,
            };
            
            return returnVector;
        }

        static std::string ToString(ControllerComparisonType value)
        {
            switch (value)
            {
                case ControllerComparisonType::Unknown: return "Unknown";
                case ControllerComparisonType::Greater: return "Greater";
                case ControllerComparisonType::Less: return "Less";
                case ControllerComparisonType::Equals: return "Equals";
            }
            
            return "Unknown";
        }

        static ControllerComparisonType FromString(std::string value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "Unknown") return ControllerComparisonType::Unknown;
                if (value == "Greater") return ControllerComparisonType::Greater;
                if (value == "Less") return ControllerComparisonType::Less;
                if (value == "Equals") return ControllerComparisonType::Equals;
            }
            else
            {
                std::string valueLower = StringHelpers::ToLower(value); 
                if (valueLower == "unknown") return ControllerComparisonType::Unknown;
                if (valueLower == "greater") return ControllerComparisonType::Greater;
                if (valueLower == "less") return ControllerComparisonType::Less;
                if (valueLower == "equals") return ControllerComparisonType::Equals;
            }
            
            return "Unknown";
        }
    };
}
