#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace SuperGameTools
{
    /// <summary>
    /// Defines options selected to view debug information in the viewport.
    /// </summary>
    enum class ViewportDebugOption : uint8_t
    {
        None = 0,

        /// <summary>
        /// Display hitboxes around the Gizmos
        /// </summary>
        Gizmo = 1 << 0,

        /// <summary>
        /// Display hitboxes around the GameObject
        /// </summary>
        GameObject = 1 << 1,

        /// <summary>
        /// Display where the cursor counts its location as.
        /// </summary>
        Cursor = 1 << 2,
    };

    /// <summary>
    /// Combines flags. For example: auto var = left | right; returns a bitflag containing both left and right. 
    /// </summary>
    inline ViewportDebugOption operator | (ViewportDebugOption lhs, ViewportDebugOption rhs)
    {
        using T = std::underlying_type_t <ViewportDebugOption>;
        return static_cast<ViewportDebugOption>(static_cast<T>(lhs) | static_cast<T>(rhs));
    }

    /// <summary>
    /// Combines flags in assignment. For example: left |= right; Adds right flag to left variable. 
    /// </summary>
    inline ViewportDebugOption& operator |= (ViewportDebugOption& lhs, ViewportDebugOption rhs)
    {
        lhs = lhs | rhs;
        return lhs;
    }

    /// <summary>
    /// Gets the intersection of flags. Mostly used as in this example: bool isSet = ((state & flag1) == flag1); 
    /// Is set would be true if state has the flag. Also this can be combined with ~ to remove a flag (see below). 
    /// HasFlag will also do this for you in nicer syntax. 
    /// </summary>
    inline ViewportDebugOption operator & (ViewportDebugOption lhs, ViewportDebugOption rhs)
    {
        using T = std::underlying_type_t <ViewportDebugOption>;
        return static_cast<ViewportDebugOption>(static_cast<T>(lhs) & static_cast<T>(rhs));
    }

    /// <summary>
    /// Returns the intersection of the flags in an assignment. 
    /// Mostly combined with ~ as in this example: state &= ~flagToRemove; 
    /// This would remove flagToRemove from the given state. 
    /// </summary>
    inline ViewportDebugOption& operator &= (ViewportDebugOption& lhs, ViewportDebugOption rhs)
    {
        lhs = lhs & rhs;
        return lhs;
    }

    /// <summary>
    /// Performs an XOR operation on the left and right and returns the result. 
    /// This is mostly which to compare two sets of flags and to figure out where they differ. 
    /// left = flag1; right = flag1 | flag2; different = left ^ right; 
    /// different in this example will be flag2.
    /// Keep in mind you would not know where the differences are you would need to do this: 
    /// bool checkLeft = different & left; - nothing removed / added. 
    /// bool checkRight = different & right; - flag2 added. 
    /// </summary>
    inline ViewportDebugOption operator ^ (ViewportDebugOption lhs, ViewportDebugOption rhs)
    {
        using T = std::underlying_type_t <ViewportDebugOption>;
        return static_cast<ViewportDebugOption>(static_cast<T>(lhs) ^ static_cast<T>(rhs));
    }

    /// <summary>
    /// Performs an XOR operation on the flag which results in a toggle assignment.
    /// Example: state ^= flag1; This would toggle whether flag1 is on within the enum.
    /// </summary>
    inline ViewportDebugOption& operator ^= (ViewportDebugOption& lhs, ViewportDebugOption rhs)
    {
        lhs = lhs ^ rhs;
        return lhs;
    }

    /// <summary>
    /// Returns the opposite or 'unset' or 'invert' flag of the given. 
    /// Mostly combined with &= as in this example: state &= ~flagToRemove; 
    /// This would remove flagToRemove from the given state. 
    /// </summary>
    inline ViewportDebugOption operator ~ (ViewportDebugOption lhs)
    {
        using T = std::underlying_type_t <ViewportDebugOption>;
        return static_cast<ViewportDebugOption>(~static_cast<T>(lhs));
    }

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EViewportDebugOption
    {
    public:
        static ViewportDebugOption Min() { return ViewportDebugOption::None; }
        static ViewportDebugOption Max() { return ViewportDebugOption::Cursor; }

        static ViewportDebugOption* ToArray()
        {
            static ViewportDebugOption returnArray[] =
            {
                ViewportDebugOption::None,
                ViewportDebugOption::Gizmo,
                ViewportDebugOption::GameObject,
                ViewportDebugOption::Cursor,
            };
            
            return returnArray;
        }

        static std::vector<ViewportDebugOption> ToVector()
        {
            static std::vector<ViewportDebugOption> returnVector =
            {
                ViewportDebugOption::None,
                ViewportDebugOption::Gizmo,
                ViewportDebugOption::GameObject,
                ViewportDebugOption::Cursor,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "None",
                "Gizmo",
                "GameObject",
                "Cursor",
            };
            
            return returnVector;
        }

        static std::string* ToArrayValues()
        {
            static std::string returnArray[] =
            {
                "None",
                "Gizmo",
                "GameObject",
                "Cursor",
            };
            
            return returnArray;
        }

        static std::string ToString(ViewportDebugOption value)
        {
            if(value == ViewportDebugOption::None)
            {
                return "None";
            }
            
            std::vector<std::string> entries;
            if(HasFlag(value,ViewportDebugOption::None))
            {
                entries.emplace_back("None");
            }
            if(HasFlag(value,ViewportDebugOption::Gizmo))
            {
                entries.emplace_back("Gizmo");
            }
            if(HasFlag(value,ViewportDebugOption::GameObject))
            {
                entries.emplace_back("GameObject");
            }
            if(HasFlag(value,ViewportDebugOption::Cursor))
            {
                entries.emplace_back("Cursor");
            }
            
            std::string returnToString = {};
            for (const std::string& entry : entries)
            {
                if (returnToString.empty())
                {
                    returnToString = entry;
                }
                else
                {
                    returnToString += " | " + entry;
                }
            }
            return returnToString;
        }

        static ViewportDebugOption FromString(const std::string& value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "None") return ViewportDebugOption::None;
                if (value == "Gizmo") return ViewportDebugOption::Gizmo;
                if (value == "GameObject") return ViewportDebugOption::GameObject;
                if (value == "Cursor") return ViewportDebugOption::Cursor;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "none") return ViewportDebugOption::None;
                if (valueLower == "gizmo") return ViewportDebugOption::Gizmo;
                if (valueLower == "gameobject") return ViewportDebugOption::GameObject;
                if (valueLower == "cursor") return ViewportDebugOption::Cursor;
            }
            
            return ViewportDebugOption::None;
        }

        /// <summary>
        /// Test to see whether value has the given flag.
        /// </summary>
        /// <param name="origin">Origin to look for flag in. </param>
        /// <param name="lookFor">Value to look for. </param>
        /// <returns>True means has flag. </returns>
        static bool HasFlag(ViewportDebugOption origin, ViewportDebugOption lookFor)
        {
            return (origin & lookFor) != ViewportDebugOption::None;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
