#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace SuperGameTools
{
    /// <summary>
    /// Describes the different viewport tools.
    /// </summary>
    enum class ViewportToolsType : uint8_t
    {
        /// <summary>
        /// Only used for unsuccessful parsing.
        /// </summary>
        Unknown,

        /// <summary>
        /// Select, used to select items in the scene.
        /// </summary>
        Select,

        /// <summary>
        /// Move, used to move items in the scene.
        /// </summary>
        Move,
    };

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EViewportToolsType
    {
    public:
        static ViewportToolsType Min() { return ViewportToolsType::Select; }
        static ViewportToolsType Max() { return ViewportToolsType::Move; }

        static ViewportToolsType* ToArray()
        {
            static ViewportToolsType returnArray[] =
            {
                ViewportToolsType::Select,
                ViewportToolsType::Move,
            };
            
            return returnArray;
        }

        static std::vector<ViewportToolsType> ToVector()
        {
            static std::vector<ViewportToolsType> returnVector =
            {
                ViewportToolsType::Select,
                ViewportToolsType::Move,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "Select",
                "Move",
            };
            
            return returnVector;
        }

        static std::string* ToArrayValues()
        {
            static std::string returnArray[] =
            {
                "Select",
                "Move",
            };
            
            return returnArray;
        }

        static std::string ToString(ViewportToolsType value)
        {
            switch (value)
            {
                case ViewportToolsType::Unknown: return "Unknown";
                case ViewportToolsType::Select: return "Select";
                case ViewportToolsType::Move: return "Move";
            }
            
            return "Unknown";
        }

        static ViewportToolsType FromString(const std::string& value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "Unknown") return ViewportToolsType::Unknown;
                if (value == "Select") return ViewportToolsType::Select;
                if (value == "Move") return ViewportToolsType::Move;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "unknown") return ViewportToolsType::Unknown;
                if (valueLower == "select") return ViewportToolsType::Select;
                if (valueLower == "move") return ViewportToolsType::Move;
            }
            
            return ViewportToolsType::Unknown;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
