#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace SuperGameTools
{
    /// <summary>
    /// Given to a window directly to change the appearence or behaviour.
    /// </summary>
    enum class WindowFlags : uint32_t
    {
        None = 0,

        /// <summary>
        /// Disable title-bar
        /// </summary>
        NoTitleBar = 1 << 0,

        /// <summary>
        /// Disable user resizing with the lower-right grip
        /// </summary>
        NoResize = 1 << 1,

        /// <summary>
        /// Disable user moving the window
        /// </summary>
        NoMove = 1 << 2,

        /// <summary>
        /// Disable scrollbars (window can still scroll with mouse or programmatically)
        /// </summary>
        NoScrollbar = 1 << 3,

        /// <summary>
        /// Disable user vertically scrolling with mouse wheel. On child window, mouse wheel will be forwarded to the parent unless NoScrollbar is also set.
        /// </summary>
        NoScrollWithMouse = 1 << 4,

        /// <summary>
        /// Disable user collapsing window by double-clicking on it. Also referred to as Window Menu Button (e.g. within a docking node).
        /// </summary>
        NoCollapse = 1 << 5,

        /// <summary>
        /// Resize every window to its content every frame
        /// </summary>
        AlwaysAutoResize = 1 << 6,

        /// <summary>
        /// Disable drawing background color (WindowBg, etc.) and outside border. Similar as using SetNextWindowBgAlpha(0.0f).
        /// </summary>
        NoBackground = 1 << 7,

        /// <summary>
        /// Never load/save settings in .ini file
        /// </summary>
        NoSavedSettings = 1 << 8,

        /// <summary>
        /// Disable catching mouse, hovering test with pass through.
        /// </summary>
        NoMouseInputs = 1 << 9,

        /// <summary>
        /// Has a menu-bar
        /// </summary>
        MenuBar = 1 << 10,

        /// <summary>
        /// Allow horizontal scrollbar to appear (off by default). You may use SetNextWindowContentSize(ImVec2(width,0.0f));
        /// prior to calling Begin() to specify width. Read code in imgui_demo in the "Horizontal Scrolling" section.
        /// </summary>
        HorizontalScrollbar = 1 << 11,

        /// <summary>
        /// Disable taking focus when transitioning from hidden to visible state
        /// </summary>
        NoFocusOnAppearing = 1 << 12,

        /// <summary>
        /// Disable bringing window to front when taking focus (e.g. clicking on it or programmatically giving it focus)
        /// </summary>
        NoBringToFrontOnFocus = 1 << 13,

        /// <summary>
        /// Always show vertical scrollbar (even if ContentSize.y &lt Size.y)
        /// </summary>
        AlwaysVerticalScrollbar = 1 << 14,

        /// <summary>
        /// Always show horizontal scrollbar (even if ContentSize.x &lt Size.x)
        /// </summary>
        AlwaysHorizontalScrollbar = 1 << 15,

        /// <summary>
        /// No keyboard/gamepad navigation within the window
        /// </summary>
        NoNavInputs = 1 << 16,

        /// <summary>
        /// No focusing toward this window with keyboard/gamepad navigation (e.g. skipped by CTRL+TAB)
        /// </summary>
        NoNavFocus = 1 << 17,

        /// <summary>
        /// Display a dot next to the title. When used in a tab/docking context, tab is selected when clicking the X + closure is not assumed (will wait for user to stop submitting the tab). Otherwise closure is assumed when pressing the X, so if you keep submitting the tab may reappear at end of tab bar.
        /// </summary>
        UnsavedDocument = 1 << 18,

        /// <summary>
        /// Disable docking of this window
        /// </summary>
        NoDocking = 1 << 19,

        NoNav = 1 << 20,

        NoDecoration = 1 << 21,

        NoInputs = 1 << 22,
    };

    /// <summary>
    /// Combines flags. For example: auto var = left | right; returns a bitflag containing both left and right. 
    /// </summary>
    inline WindowFlags operator | (WindowFlags lhs, WindowFlags rhs)
    {
        using T = std::underlying_type_t <WindowFlags>;
        return static_cast<WindowFlags>(static_cast<T>(lhs) | static_cast<T>(rhs));
    }

    /// <summary>
    /// Combines flags in assignment. For example: left |= right; Adds right flag to left variable. 
    /// </summary>
    inline WindowFlags& operator |= (WindowFlags& lhs, WindowFlags rhs)
    {
        lhs = lhs | rhs;
        return lhs;
    }

    /// <summary>
    /// Gets the intersection of flags. Mostly used as in this example: bool isSet = ((state & flag1) == flag1); 
    /// Is set would be true if state has the flag. Also this can be combined with ~ to remove a flag (see below). 
    /// HasFlag will also do this for you in nicer syntax. 
    /// </summary>
    inline WindowFlags operator & (WindowFlags lhs, WindowFlags rhs)
    {
        using T = std::underlying_type_t <WindowFlags>;
        return static_cast<WindowFlags>(static_cast<T>(lhs) & static_cast<T>(rhs));
    }

    /// <summary>
    /// Returns the intersection of the flags in an assignment. 
    /// Mostly combined with ~ as in this example: state &= ~flagToRemove; 
    /// This would remove flagToRemove from the given state. 
    /// </summary>
    inline WindowFlags& operator &= (WindowFlags& lhs, WindowFlags rhs)
    {
        lhs = lhs & rhs;
        return lhs;
    }

    /// <summary>
    /// Performs an XOR operation on the left and right and returns the result. 
    /// This is mostly which to compare two sets of flags and to figure out where they differ. 
    /// left = flag1; right = flag1 | flag2; different = left ^ right; 
    /// different in this example will be flag2.
    /// Keep in mind you would not know where the differences are you would need to do this: 
    /// bool checkLeft = different & left; - nothing removed / added. 
    /// bool checkRight = different & right; - flag2 added. 
    /// </summary>
    inline WindowFlags operator ^ (WindowFlags lhs, WindowFlags rhs)
    {
        using T = std::underlying_type_t <WindowFlags>;
        return static_cast<WindowFlags>(static_cast<T>(lhs) ^ static_cast<T>(rhs));
    }

    /// <summary>
    /// Performs an XOR operation on the flag which results in a toggle assignment.
    /// Example: state ^= flag1; This would toggle whether flag1 is on within the enum.
    /// </summary>
    inline WindowFlags& operator ^= (WindowFlags& lhs, WindowFlags rhs)
    {
        lhs = lhs ^ rhs;
        return lhs;
    }

    /// <summary>
    /// Returns the opposite or 'unset' or 'invert' flag of the given. 
    /// Mostly combined with &= as in this example: state &= ~flagToRemove; 
    /// This would remove flagToRemove from the given state. 
    /// </summary>
    inline WindowFlags operator ~ (WindowFlags lhs)
    {
        using T = std::underlying_type_t <WindowFlags>;
        return static_cast<WindowFlags>(~static_cast<T>(lhs));
    }

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EWindowFlags
    {
    public:
        static WindowFlags Min() { return WindowFlags::None; }
        static WindowFlags Max() { return WindowFlags::NoInputs; }

        static WindowFlags* ToArray()
        {
            static WindowFlags returnArray[] =
            {
                WindowFlags::None,
                WindowFlags::NoTitleBar,
                WindowFlags::NoResize,
                WindowFlags::NoMove,
                WindowFlags::NoScrollbar,
                WindowFlags::NoScrollWithMouse,
                WindowFlags::NoCollapse,
                WindowFlags::AlwaysAutoResize,
                WindowFlags::NoBackground,
                WindowFlags::NoSavedSettings,
                WindowFlags::NoMouseInputs,
                WindowFlags::MenuBar,
                WindowFlags::HorizontalScrollbar,
                WindowFlags::NoFocusOnAppearing,
                WindowFlags::NoBringToFrontOnFocus,
                WindowFlags::AlwaysVerticalScrollbar,
                WindowFlags::AlwaysHorizontalScrollbar,
                WindowFlags::NoNavInputs,
                WindowFlags::NoNavFocus,
                WindowFlags::UnsavedDocument,
                WindowFlags::NoDocking,
                WindowFlags::NoNav,
                WindowFlags::NoDecoration,
                WindowFlags::NoInputs,
            };
            
            return returnArray;
        }

        static std::vector<WindowFlags> ToVector()
        {
            static std::vector<WindowFlags> returnVector =
            {
                WindowFlags::None,
                WindowFlags::NoTitleBar,
                WindowFlags::NoResize,
                WindowFlags::NoMove,
                WindowFlags::NoScrollbar,
                WindowFlags::NoScrollWithMouse,
                WindowFlags::NoCollapse,
                WindowFlags::AlwaysAutoResize,
                WindowFlags::NoBackground,
                WindowFlags::NoSavedSettings,
                WindowFlags::NoMouseInputs,
                WindowFlags::MenuBar,
                WindowFlags::HorizontalScrollbar,
                WindowFlags::NoFocusOnAppearing,
                WindowFlags::NoBringToFrontOnFocus,
                WindowFlags::AlwaysVerticalScrollbar,
                WindowFlags::AlwaysHorizontalScrollbar,
                WindowFlags::NoNavInputs,
                WindowFlags::NoNavFocus,
                WindowFlags::UnsavedDocument,
                WindowFlags::NoDocking,
                WindowFlags::NoNav,
                WindowFlags::NoDecoration,
                WindowFlags::NoInputs,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "None",
                "NoTitleBar",
                "NoResize",
                "NoMove",
                "NoScrollbar",
                "NoScrollWithMouse",
                "NoCollapse",
                "AlwaysAutoResize",
                "NoBackground",
                "NoSavedSettings",
                "NoMouseInputs",
                "MenuBar",
                "HorizontalScrollbar",
                "NoFocusOnAppearing",
                "NoBringToFrontOnFocus",
                "AlwaysVerticalScrollbar",
                "AlwaysHorizontalScrollbar",
                "NoNavInputs",
                "NoNavFocus",
                "UnsavedDocument",
                "NoDocking",
                "NoNav",
                "NoDecoration",
                "NoInputs",
            };
            
            return returnVector;
        }

        static std::string ToString(WindowFlags value)
        {
            if(value == WindowFlags::None)
            {
                return "None";
            }
            
            std::vector<std::string> entries;
            if(HasFlag(value,WindowFlags::None))
            {
                entries.emplace_back("None");
            }
            if(HasFlag(value,WindowFlags::NoTitleBar))
            {
                entries.emplace_back("NoTitleBar");
            }
            if(HasFlag(value,WindowFlags::NoResize))
            {
                entries.emplace_back("NoResize");
            }
            if(HasFlag(value,WindowFlags::NoMove))
            {
                entries.emplace_back("NoMove");
            }
            if(HasFlag(value,WindowFlags::NoScrollbar))
            {
                entries.emplace_back("NoScrollbar");
            }
            if(HasFlag(value,WindowFlags::NoScrollWithMouse))
            {
                entries.emplace_back("NoScrollWithMouse");
            }
            if(HasFlag(value,WindowFlags::NoCollapse))
            {
                entries.emplace_back("NoCollapse");
            }
            if(HasFlag(value,WindowFlags::AlwaysAutoResize))
            {
                entries.emplace_back("AlwaysAutoResize");
            }
            if(HasFlag(value,WindowFlags::NoBackground))
            {
                entries.emplace_back("NoBackground");
            }
            if(HasFlag(value,WindowFlags::NoSavedSettings))
            {
                entries.emplace_back("NoSavedSettings");
            }
            if(HasFlag(value,WindowFlags::NoMouseInputs))
            {
                entries.emplace_back("NoMouseInputs");
            }
            if(HasFlag(value,WindowFlags::MenuBar))
            {
                entries.emplace_back("MenuBar");
            }
            if(HasFlag(value,WindowFlags::HorizontalScrollbar))
            {
                entries.emplace_back("HorizontalScrollbar");
            }
            if(HasFlag(value,WindowFlags::NoFocusOnAppearing))
            {
                entries.emplace_back("NoFocusOnAppearing");
            }
            if(HasFlag(value,WindowFlags::NoBringToFrontOnFocus))
            {
                entries.emplace_back("NoBringToFrontOnFocus");
            }
            if(HasFlag(value,WindowFlags::AlwaysVerticalScrollbar))
            {
                entries.emplace_back("AlwaysVerticalScrollbar");
            }
            if(HasFlag(value,WindowFlags::AlwaysHorizontalScrollbar))
            {
                entries.emplace_back("AlwaysHorizontalScrollbar");
            }
            if(HasFlag(value,WindowFlags::NoNavInputs))
            {
                entries.emplace_back("NoNavInputs");
            }
            if(HasFlag(value,WindowFlags::NoNavFocus))
            {
                entries.emplace_back("NoNavFocus");
            }
            if(HasFlag(value,WindowFlags::UnsavedDocument))
            {
                entries.emplace_back("UnsavedDocument");
            }
            if(HasFlag(value,WindowFlags::NoDocking))
            {
                entries.emplace_back("NoDocking");
            }
            if(HasFlag(value,WindowFlags::NoNav))
            {
                entries.emplace_back("NoNav");
            }
            if(HasFlag(value,WindowFlags::NoDecoration))
            {
                entries.emplace_back("NoDecoration");
            }
            if(HasFlag(value,WindowFlags::NoInputs))
            {
                entries.emplace_back("NoInputs");
            }
            
            std::string returnToString = {};
            for (const std::string& entry : entries)
            {
                if (returnToString.empty())
                {
                    returnToString = entry;
                }
                else
                {
                    returnToString += " | " + entry;
                }
            }
            return returnToString;
        }

        static WindowFlags FromString(const std::string& value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "None") return WindowFlags::None;
                if (value == "NoTitleBar") return WindowFlags::NoTitleBar;
                if (value == "NoResize") return WindowFlags::NoResize;
                if (value == "NoMove") return WindowFlags::NoMove;
                if (value == "NoScrollbar") return WindowFlags::NoScrollbar;
                if (value == "NoScrollWithMouse") return WindowFlags::NoScrollWithMouse;
                if (value == "NoCollapse") return WindowFlags::NoCollapse;
                if (value == "AlwaysAutoResize") return WindowFlags::AlwaysAutoResize;
                if (value == "NoBackground") return WindowFlags::NoBackground;
                if (value == "NoSavedSettings") return WindowFlags::NoSavedSettings;
                if (value == "NoMouseInputs") return WindowFlags::NoMouseInputs;
                if (value == "MenuBar") return WindowFlags::MenuBar;
                if (value == "HorizontalScrollbar") return WindowFlags::HorizontalScrollbar;
                if (value == "NoFocusOnAppearing") return WindowFlags::NoFocusOnAppearing;
                if (value == "NoBringToFrontOnFocus") return WindowFlags::NoBringToFrontOnFocus;
                if (value == "AlwaysVerticalScrollbar") return WindowFlags::AlwaysVerticalScrollbar;
                if (value == "AlwaysHorizontalScrollbar") return WindowFlags::AlwaysHorizontalScrollbar;
                if (value == "NoNavInputs") return WindowFlags::NoNavInputs;
                if (value == "NoNavFocus") return WindowFlags::NoNavFocus;
                if (value == "UnsavedDocument") return WindowFlags::UnsavedDocument;
                if (value == "NoDocking") return WindowFlags::NoDocking;
                if (value == "NoNav") return WindowFlags::NoNav;
                if (value == "NoDecoration") return WindowFlags::NoDecoration;
                if (value == "NoInputs") return WindowFlags::NoInputs;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "none") return WindowFlags::None;
                if (valueLower == "notitlebar") return WindowFlags::NoTitleBar;
                if (valueLower == "noresize") return WindowFlags::NoResize;
                if (valueLower == "nomove") return WindowFlags::NoMove;
                if (valueLower == "noscrollbar") return WindowFlags::NoScrollbar;
                if (valueLower == "noscrollwithmouse") return WindowFlags::NoScrollWithMouse;
                if (valueLower == "nocollapse") return WindowFlags::NoCollapse;
                if (valueLower == "alwaysautoresize") return WindowFlags::AlwaysAutoResize;
                if (valueLower == "nobackground") return WindowFlags::NoBackground;
                if (valueLower == "nosavedsettings") return WindowFlags::NoSavedSettings;
                if (valueLower == "nomouseinputs") return WindowFlags::NoMouseInputs;
                if (valueLower == "menubar") return WindowFlags::MenuBar;
                if (valueLower == "horizontalscrollbar") return WindowFlags::HorizontalScrollbar;
                if (valueLower == "nofocusonappearing") return WindowFlags::NoFocusOnAppearing;
                if (valueLower == "nobringtofrontonfocus") return WindowFlags::NoBringToFrontOnFocus;
                if (valueLower == "alwaysverticalscrollbar") return WindowFlags::AlwaysVerticalScrollbar;
                if (valueLower == "alwayshorizontalscrollbar") return WindowFlags::AlwaysHorizontalScrollbar;
                if (valueLower == "nonavinputs") return WindowFlags::NoNavInputs;
                if (valueLower == "nonavfocus") return WindowFlags::NoNavFocus;
                if (valueLower == "unsaveddocument") return WindowFlags::UnsavedDocument;
                if (valueLower == "nodocking") return WindowFlags::NoDocking;
                if (valueLower == "nonav") return WindowFlags::NoNav;
                if (valueLower == "nodecoration") return WindowFlags::NoDecoration;
                if (valueLower == "noinputs") return WindowFlags::NoInputs;
            }
            
            return WindowFlags::None;
        }

        /// <summary>
        /// Test to see whether value has the given flag.
        /// </summary>
        /// <param name="origin">Origin to look for flag in. </param>
        /// <param name="lookFor">Value to look for. </param>
        /// <returns>True means has flag. </returns>
        static bool HasFlag(WindowFlags origin, WindowFlags lookFor)
        {
            return (origin & lookFor) != WindowFlags::None;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
