#pragma once
#include <Imgui/External/imgui.h>
#include "WindowFlags.h"


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnumConverter. See Tools for details.
// +------------------------------+
namespace SuperGameTools
{
    class WindowFlagsToImGuiConverter
    {
    public:
        /// <summary>
        /// Converts from the enum ImGuiWindowFlags_ to WindowFlags::WindowFlags
        /// </summary>
        /// <remarks>
        /// This method is built to work independent of the super enum methods to enable conversation from external enums to internal.
        /// Therefore some methods are duplicated and some implementation more explicit as it is unknown as to whether the enums requested
        /// are super enums.
        /// </remarks>
        static WindowFlags Convert(ImGuiWindowFlags_ input)
        {
            if(input == ImGuiWindowFlags_None)
            {
                return WindowFlags::None;
            }

            WindowFlags returnNewValue = WindowFlags::None; 
            if(HasFlag(input, ImGuiWindowFlags_NoTitleBar))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoTitleBar);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoResize))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoResize);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoMove))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoMove);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoScrollbar))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoScrollbar);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoScrollWithMouse))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoScrollWithMouse);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoCollapse))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoCollapse);
            }

            if(HasFlag(input, ImGuiWindowFlags_AlwaysAutoResize))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::AlwaysAutoResize);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoBackground))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoBackground);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoSavedSettings))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoSavedSettings);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoMouseInputs))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoMouseInputs);
            }

            if(HasFlag(input, ImGuiWindowFlags_MenuBar))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::MenuBar);
            }

            if(HasFlag(input, ImGuiWindowFlags_HorizontalScrollbar))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::HorizontalScrollbar);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoFocusOnAppearing))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoFocusOnAppearing);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoBringToFrontOnFocus))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoBringToFrontOnFocus);
            }

            if(HasFlag(input, ImGuiWindowFlags_AlwaysVerticalScrollbar))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::AlwaysVerticalScrollbar);
            }

            if(HasFlag(input, ImGuiWindowFlags_AlwaysHorizontalScrollbar))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::AlwaysHorizontalScrollbar);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoNavInputs))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoNavInputs);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoNavFocus))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoNavFocus);
            }

            if(HasFlag(input, ImGuiWindowFlags_UnsavedDocument))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::UnsavedDocument);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoDocking))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoDocking);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoNav))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoNav);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoDecoration))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoDecoration);
            }

            if(HasFlag(input, ImGuiWindowFlags_NoInputs))
            {
                returnNewValue = static_cast<WindowFlags>(returnNewValue | WindowFlags::NoInputs);
            }

            return returnNewValue;
        }
        
        /// <summary>
        /// Converts from the enum WindowFlags::WindowFlags to ImGuiWindowFlags_
        /// </summary>
        /// <remarks>
        /// This method is built to work independent of the super enum methods to enable conversation from external enums to internal.
        /// Therefore some methods are duplicated and some implementation more explicit as it is unknown as to whether the enums requested
        /// are super enums.
        /// </remarks>
        static ImGuiWindowFlags_ Convert(WindowFlags input)
        {
            if(input == WindowFlags::None)
            {
                return ImGuiWindowFlags_None;
            }

            ImGuiWindowFlags_ returnNewValue = ImGuiWindowFlags_None; 
            if(HasFlag(input, WindowFlags::NoTitleBar))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoTitleBar);
            }

            if(HasFlag(input, WindowFlags::NoResize))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoResize);
            }

            if(HasFlag(input, WindowFlags::NoMove))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoMove);
            }

            if(HasFlag(input, WindowFlags::NoScrollbar))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoScrollbar);
            }

            if(HasFlag(input, WindowFlags::NoScrollWithMouse))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoScrollWithMouse);
            }

            if(HasFlag(input, WindowFlags::NoCollapse))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoCollapse);
            }

            if(HasFlag(input, WindowFlags::AlwaysAutoResize))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_AlwaysAutoResize);
            }

            if(HasFlag(input, WindowFlags::NoBackground))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoBackground);
            }

            if(HasFlag(input, WindowFlags::NoSavedSettings))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoSavedSettings);
            }

            if(HasFlag(input, WindowFlags::NoMouseInputs))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoMouseInputs);
            }

            if(HasFlag(input, WindowFlags::MenuBar))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_MenuBar);
            }

            if(HasFlag(input, WindowFlags::HorizontalScrollbar))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_HorizontalScrollbar);
            }

            if(HasFlag(input, WindowFlags::NoFocusOnAppearing))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoFocusOnAppearing);
            }

            if(HasFlag(input, WindowFlags::NoBringToFrontOnFocus))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoBringToFrontOnFocus);
            }

            if(HasFlag(input, WindowFlags::AlwaysVerticalScrollbar))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_AlwaysVerticalScrollbar);
            }

            if(HasFlag(input, WindowFlags::AlwaysHorizontalScrollbar))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_AlwaysHorizontalScrollbar);
            }

            if(HasFlag(input, WindowFlags::NoNavInputs))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoNavInputs);
            }

            if(HasFlag(input, WindowFlags::NoNavFocus))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoNavFocus);
            }

            if(HasFlag(input, WindowFlags::UnsavedDocument))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_UnsavedDocument);
            }

            if(HasFlag(input, WindowFlags::NoDocking))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoDocking);
            }

            if(HasFlag(input, WindowFlags::NoNav))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoNav);
            }

            if(HasFlag(input, WindowFlags::NoDecoration))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoDecoration);
            }

            if(HasFlag(input, WindowFlags::NoInputs))
            {
                returnNewValue = static_cast<ImGuiWindowFlags_>(returnNewValue | ImGuiWindowFlags_NoInputs);
            }

            return returnNewValue;
        }
        
        private:

            /// <summary>
            /// Test to see whether value has the given flag.
            /// </summary>
            /// <param name="origin">Origin to look for flag in. </param>
            /// <param name="lookFor">Value to look for. </param>
            /// <returns>True means has flag. </returns>
            static bool HasFlag(WindowFlags origin, WindowFlags lookFor)
            {
                return (origin & lookFor) != WindowFlags::None;
            }

            /// <summary>
            /// Test to see whether value has the given flag.
            /// </summary>
            /// <param name="origin">Origin to look for flag in. </param>
            /// <param name="lookFor">Value to look for. </param>
            /// <returns>True means has flag. </returns>
            static bool HasFlag(ImGuiWindowFlags_ origin, ImGuiWindowFlags_ lookFor)
            {
                return (origin & lookFor) != ImGuiWindowFlags_None;
            }
        };
}
