#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace FatedQuestLibraries
{
    /// <summary>
    /// Describes the type of a single aspect of a markdown document.
    /// </summary>
    enum class MarkdownElementType : uint8_t
    {
        /// <summary>
        /// Only used for unsuccessful parsing.
        /// </summary>
        Unknown = 0,

        /// <summary>
        /// A paragraph of text.
        /// </summary>
        Paragraph,

        /// <summary>
        /// Top Level Heading
        /// </summary>
        Heading1,

        /// <summary>
        /// Tile is hovered or should be rendered as such.
        /// If this is not paired with an action assume only hover has occured.
        /// </summary>
        Table,
    };

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EMarkdownElementType
    {
    public:
        static MarkdownElementType Min() { return MarkdownElementType::Paragraph; }
        static MarkdownElementType Max() { return MarkdownElementType::Table; }

        static MarkdownElementType* ToArray()
        {
            static MarkdownElementType returnArray[] =
            {
                MarkdownElementType::Paragraph,
                MarkdownElementType::Heading1,
                MarkdownElementType::Table,
            };
            
            return returnArray;
        }

        static std::vector<MarkdownElementType> ToVector()
        {
            static std::vector<MarkdownElementType> returnVector =
            {
                MarkdownElementType::Paragraph,
                MarkdownElementType::Heading1,
                MarkdownElementType::Table,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "Paragraph",
                "Heading1",
                "Table",
            };
            
            return returnVector;
        }

        static std::string ToString(MarkdownElementType value)
        {
            switch (value)
            {
                case MarkdownElementType::Unknown: return "Unknown";
                case MarkdownElementType::Paragraph: return "Paragraph";
                case MarkdownElementType::Heading1: return "Heading1";
                case MarkdownElementType::Table: return "Table";
            }
            
            return "Unknown";
        }

        static MarkdownElementType FromString(std::string value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "Unknown") return MarkdownElementType::Unknown;
                if (value == "Paragraph") return MarkdownElementType::Paragraph;
                if (value == "Heading1") return MarkdownElementType::Heading1;
                if (value == "Table") return MarkdownElementType::Table;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "unknown") return MarkdownElementType::Unknown;
                if (valueLower == "paragraph") return MarkdownElementType::Paragraph;
                if (valueLower == "heading1") return MarkdownElementType::Heading1;
                if (valueLower == "table") return MarkdownElementType::Table;
            }
            
            return MarkdownElementType::Unknown;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
