#pragma once
// +------------------------------+
// Generated by EnumGenerator as an
// SuperEnum. See Tools for details.
// Date: 2024/11/25 21:14:41
// +------------------------------+
namespace SuperGameEngine
{
    enum class ControllerComparisonType
    {
        Entry,
        EntryTwo,
        EntryThree,
    }
}
