#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace SuperEnumGenerator
{
    /// <summary>
    /// How to match two enums (convert them) together.
    /// </summary>
    enum class SuperEnumConverterType : uint8_t
    {
        /// <summary>
        /// Only used for unsuccessful parsing.
        /// </summary>
        Unknown,

        /// <summary>
        /// Enums are simply values and should match one another.
        /// </summary>
        Standard,

        /// <summary>
        /// Values are a part of bit flags and may represent multiple values. When matching consider this.
        /// </summary>
        BitFlag,
    };

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class ESuperEnumConverterType
    {
    public:
        static SuperEnumConverterType Min() { return SuperEnumConverterType::Standard; }
        static SuperEnumConverterType Max() { return SuperEnumConverterType::BitFlag; }

        static SuperEnumConverterType* ToArray()
        {
            static SuperEnumConverterType returnArray[] =
            {
                SuperEnumConverterType::Standard,
                SuperEnumConverterType::BitFlag,
            };
            
            return returnArray;
        }

        static std::vector<SuperEnumConverterType> ToVector()
        {
            static std::vector<SuperEnumConverterType> returnVector =
            {
                SuperEnumConverterType::Standard,
                SuperEnumConverterType::BitFlag,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "Standard",
                "BitFlag",
            };
            
            return returnVector;
        }

        static std::string* ToArrayValues()
        {
            static std::string returnArray[] =
            {
                "Standard",
                "BitFlag",
            };
            
            return returnArray;
        }

        static std::string ToString(SuperEnumConverterType value)
        {
            switch (value)
            {
                case SuperEnumConverterType::Unknown: return "Unknown";
                case SuperEnumConverterType::Standard: return "Standard";
                case SuperEnumConverterType::BitFlag: return "BitFlag";
            }
            
            return "Unknown";
        }

        static SuperEnumConverterType FromString(const std::string& value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "Unknown") return SuperEnumConverterType::Unknown;
                if (value == "Standard") return SuperEnumConverterType::Standard;
                if (value == "BitFlag") return SuperEnumConverterType::BitFlag;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "unknown") return SuperEnumConverterType::Unknown;
                if (valueLower == "standard") return SuperEnumConverterType::Standard;
                if (valueLower == "bitflag") return SuperEnumConverterType::BitFlag;
            }
            
            return SuperEnumConverterType::Unknown;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
