#include "SuperEnumConverter.h"
#include "../../FatedQuest.Libraries/Logger/AllReferences.h"

using namespace SuperEnumGenerator;

SuperEnumConverter::SuperEnumConverter()
{
    m_converterType = SuperEnumConverterType::Unknown;
    m_path = {};
    m_pathPrefixToRoot = {};
}

bool SuperEnumConverter::FromString(const std::string& superEnumFile, const std::string& path)
{
    m_path = path;
    m_pathPrefixToRoot = {};
    for (size_t i = 0; i < m_path.length(); ++i)
    {
        if (m_path[i] == '\\' || m_path[i] == '/')
        {
            m_pathPrefixToRoot += "../";
        }
    }

    std::shared_ptr<StoredDocument> xml = std::make_shared<RapidXMLDocument>();
    if (!xml->Load(superEnumFile))
    {
        Log::Error("Could not parse file: " + path,
            "SuperEnumConverter::FromString(const std::string&, const std::string&)");
        return false;
    }

    std::shared_ptr<StoredDocumentNode> root = xml->GetRoot();
    if (!ParseRoot(root))
    {
        Log::Error("Could not parse root of file: " + path,
            "SuperEnumConverter::FromString(const std::string&, const std::string&)");
        return false;
    }

    std::shared_ptr<StoredDocumentNode> additionalIncludes = {};
    for (std::shared_ptr<StoredDocumentNode> child = root->GetFirstChild(); child; child = child->GetAdjacentNode())
    {
        std::string name = StringHelpers::Trim(StringHelpers::ToLower(child->Name()));
        if (name == "header")
        {
            if (!ParseHeader(child))
            {
                return false;
            }
        }
        else if (name == "namespace")
        {
            if (!ParseNamespace(child))
            {
                return false;
            }
        }
        else if (name == "enumconvertercomment")
        {
            if (!ParseEnumComment(child))
            {
                return false;
            }
        }
        else if (name == "converter")
        {
            if (!ParseConverter(child))
            {
                return false;
            }
        }
        else if (name == "additionalincludes")
        {
            additionalIncludes = child;
        }
        else if (name == "footer")
        {
            if (!ParseFooter(child))
            {
                return false;
            }
        }
        else if (name == "namespacefooter")
        {
            if (!ParseNamespaceFooter(child))
            {
                return false;
            }
        }
        else if (name == "enumdefinition")
        {
            if (!ParseEnumDefinition(child))
            {
                Log::Error("Could not parse enum definition. Path: " + m_path,
                    "SuperEnumConverter::FromString(const std::string&, const std::string&)");
                return false;
            }
        }
        //
    }

    if (additionalIncludes)
    {
        ParseAdditionalIncludes(additionalIncludes);
    }

    return true;
}

std::string SuperEnumConverter::ToString()
{
    std::string output = {};
    int indents = 0;

    output += PrintHeader(indents);
    output += "// +------------------------------+\n";
    output += "// Generated by SuperGenerator as an\n";
    output += "// SuperEnumConverter. See Tools for details.\n";
    output += "// +------------------------------+\n";

    if (m_namespace.Parsed)
    {
        output += "namespace " + m_namespace.Value + "\n";
        output += "{\n";
        ++indents;
    }

    output += PrintEnumConverter(indents);

    // This goes outside the class but in the namespace.
    output += PrintNamespaceFooter(indents);

    if (m_namespace.Parsed)
    {
        --indents;
        output += "}\n";
    }

    output += PrintFooter(indents);

    return output;

    if (m_defaultValue)
    {
        if (m_left.UseTypeAsPrefix)
        {
            output += m_left.Type + "::";
        }

        output += m_defaultValue->Left;

        output += " == ";

        if (m_right.UseTypeAsPrefix)
        {
            output += m_right.Type + "::";
        }

        output += m_defaultValue->Right;

        output += "\n";
    }

    for (const std::shared_ptr<Conversion>& conversion : m_allConversions)
    {
        if (m_left.UseTypeAsPrefix)
        {
            output += m_left.Type + "::";
        }

        output += conversion->Left;

        output += " == ";

        if (m_right.UseTypeAsPrefix)
        {
            output += m_right.Type + "::";
        }

        output += conversion->Right;

        output += "\n";
    }

    return output;
}

bool SuperEnumConverter::ParseRoot(std::shared_ptr<StoredDocumentNode> rootNode)
{
    m_converterType = SuperEnumConverterType::Standard;
    if (auto typeAttribute = rootNode->Attribute("Type", CaseSensitivity::IgnoreCase))
    {
        SuperEnumConverterType parsed = ESuperEnumConverterType::FromString(typeAttribute->Value());
        if (parsed != SuperEnumConverterType::Unknown)
        {
            m_converterType = parsed;
        }
    }

    return true;
}

bool SuperEnumConverter::ParseHeader(std::shared_ptr<StoredDocumentNode> headerNode)
{
    std::string header = StringHelpers::Trim(headerNode->Inner());
    if (header.empty())
    {
        return false;
    }

    m_header.Parsed = true;
    m_header.Value = header;

    return true;
}

bool SuperEnumConverter::ParseFooter(std::shared_ptr<StoredDocumentNode> headerNode)
{
    std::string footer = StringHelpers::Trim(headerNode->Inner());
    if (footer.empty())
    {
        return false;
    }

    m_footer.Parsed = true;
    m_footer.Value = footer;

    return true;
}

bool SuperEnumConverter::ParseNamespaceFooter(std::shared_ptr<StoredDocumentNode> headerNode)
{
    std::string footer = StringHelpers::Trim(headerNode->Inner());
    if (footer.empty())
    {
        return false;
    }

    m_namespaceFooter.Parsed = true;
    m_namespaceFooter.Value = footer;

    return true;
}

bool SuperEnumConverter::ParseNamespace(std::shared_ptr<StoredDocumentNode> namespaceNode)
{
    for (std::shared_ptr<StoredDocumentAttribute> attribute : namespaceNode->Attributes())
    {
        if (StringHelpers::ToLower(attribute->Name()) == "name")
        {
            std::string value = StringHelpers::Trim(attribute->Value());
            if (value != "")
            {
                m_namespace.Parsed = true;
                m_namespace.Value = value;
            }
        }
    }


    return m_namespace.Parsed;
}

bool SuperEnumConverter::ParseEnumComment(std::shared_ptr<StoredDocumentNode> enumNode)
{
    std::string comment = StringHelpers::Trim(enumNode->Inner());
    if (comment.empty())
    {
        return false;
    }

    m_enumComment.Parsed = true;
    m_enumComment.Value = comment;

    return true;
}

bool SuperEnumConverter::ParseConverter(std::shared_ptr<StoredDocumentNode> enumNode)
{
    for (std::shared_ptr<StoredDocumentAttribute> attribute : enumNode->Attributes())
    {
        std::string name = StringHelpers::ToLower(attribute->Name());
        if (name == "name")
        {
            std::string value = StringHelpers::Trim(attribute->Value());
            if (!value.empty())
            {
                m_enumConverterName.Parsed = true;
                m_enumConverterName.Value = value;
            }
        }
    }

    for (std::shared_ptr<StoredDocumentNode> child = enumNode->GetFirstChild(); child; child = child->GetAdjacentNode())
    {
        std::shared_ptr<Conversion> enumValue = std::make_shared<Conversion>();
        for (std::shared_ptr<StoredDocumentAttribute> attribute : child->Attributes())
        {
            std::string name = StringHelpers::ToLower(attribute->Name());
            if (name == "left")
            {
                std::string value = StringHelpers::Trim(attribute->Value());
                if (!value.empty())
                {
                    enumValue->Left = value;
                }
            }
            else if (name == "right")
            {
                std::string value = StringHelpers::Trim(attribute->Value());
                if (!value.empty())
                {
                    enumValue->Right = value;
                }
            }
        }

        if (StringHelpers::Equals("default", child->Name(), CaseSensitivity::IgnoreCase))
        {
            m_defaultValue = enumValue;
        }
        else
        {
            m_allConversions.emplace_back(enumValue);
        }
    }

    return true;
}

bool SuperEnumConverter::ParseAdditionalIncludes(std::shared_ptr<StoredDocumentNode> additionalIncludeNode)
{
    for (std::shared_ptr<StoredDocumentNode> child = additionalIncludeNode->GetFirstChild(); child; child = child->GetAdjacentNode())
    {
        std::string nodeName = StringHelpers::ToLower(child->Name());
        if (nodeName == "include")
        {
            if (std::shared_ptr<StoredDocumentAttribute> attribute = child->Attribute("rootPath", CaseSensitivity::IgnoreCase))
            {
                if (attribute->Value().empty())
                {
                    continue;
                }

                //TODO: Add this
                //AddToIncludes(attribute->Value());
            }
        }
    }

    return true;
}

bool SuperEnumConverter::ParseEnumDefinition(std::shared_ptr<StoredDocumentNode> additionalIncludeNode)
{
    auto definition = std::make_shared<EnumDefinition>();
    if (std::shared_ptr<StoredDocumentAttribute> attribute = additionalIncludeNode->Attribute("side", CaseSensitivity::IgnoreCase))
    {
        std::string sideValue = StringHelpers::ToLower(attribute->Value());
        if (sideValue == "left")
        {
            definition->IsLeft = true;
        }
        else if (sideValue == "right")
        {
            definition->IsLeft = false;
        }
    }

    if (std::shared_ptr<StoredDocumentAttribute> attribute = additionalIncludeNode->Attribute("type", CaseSensitivity::IgnoreCase))
    {
        definition->Type = attribute->Value();
    }

    if (std::shared_ptr<StoredDocumentAttribute> attribute = additionalIncludeNode->Attribute("UseTypeAsPrefix", CaseSensitivity::IgnoreCase))
    {
        std::string value = StringHelpers::ToLower(attribute->Value());
        if (value == "true")
        {
            definition->UseTypeAsPrefix = true;
        }
        else if (value == "false")
        {
            definition->UseTypeAsPrefix = false;
        }
    }

    // Do not set if there was an error.
    if (definition->Type.empty())
    {
        return false;
    }

    if (definition->IsLeft)
    {
        m_left = *definition;
    }
    else
    {
        m_right = *definition;
    }
}

std::string SuperEnumConverter::PrintIndents(int number)
{
    std::string output = "";
    for (int i = 0; i < number; ++i)
    {
        output += "    ";
    }

    return output;
}

std::string SuperEnumConverter::PrintHeader(int indents)
{
    std::string output = "";
    if (!m_header.Parsed)
    {
        return output;
    }

    std::vector<std::string> lines = StringHelpers::Split(m_header.Value, "\n");
    for (const std::string line : lines)
    {
        std::string lineTrimmed = StringHelpers::Trim(line);

        // Our standard is } on a line.
        if (lineTrimmed == "}")
        {
            --indents;
        }

        if (!lineTrimmed.empty())
        {
            output += PrintIndents(indents) + lineTrimmed + "\n";
        }

        size_t open = 0, closed = 0;
        for (size_t i = 0; i < lineTrimmed.length(); ++i)
        {
            if (lineTrimmed[i] == '{')
            {
                ++open;
            }
            else if (lineTrimmed[i] == '}')
            {
                ++closed;
            }
        }
    }

    // Any required includes would go here.
    // For this file there are none.

    output += PrintIndents(indents) + "\n";
    output += PrintIndents(indents) + "\n";

    return output;
}

std::string SuperEnumConverter::PrintFooter(int indents)
{
    std::string output = {};
    if (!m_footer.Parsed)
    {
        return output;
    }

    output = "\n";

    std::vector<std::string> lines = StringHelpers::Split(m_footer.Value, "\n");
    for (const std::string line : lines)
    {
        std::string lineTrimmed = StringHelpers::Trim(line);

        // Our standard is } on a line.
        if (lineTrimmed == "}")
        {
            --indents;
        }

        if (!lineTrimmed.empty())
        {

            output += PrintIndents(indents) + lineTrimmed + "\n";
        }

        size_t open = 0, closed = 0;
        for (size_t i = 0; i < lineTrimmed.length(); ++i)
        {
            if (lineTrimmed[i] == '{')
            {
                ++open;
            }
            else if (lineTrimmed[i] == '}')
            {
                ++closed;
            }
        }

        indents += static_cast<int>(open) - static_cast<int>(closed);
    }

    return output;
}

std::string SuperEnumConverter::PrintNamespaceFooter(int indents)
{
    std::string output = {};
    if (!m_namespaceFooter.Parsed)
    {
        return output;
    }

    output = "\n";

    std::vector<std::string> lines = StringHelpers::Split(m_namespaceFooter.Value, "\n");
    for (const std::string line : lines)
    {
        std::string lineTrimmed = StringHelpers::Trim(line);

        // Our standard is } on a line.
        if (lineTrimmed == "}")
        {
            --indents;
        }

        if (!lineTrimmed.empty())
        {
            output += PrintIndents(indents) + lineTrimmed + "\n";
        }

        size_t open = 0, closed = 0;
        for (size_t i = 0; i < lineTrimmed.length(); ++i)
        {
            if (lineTrimmed[i] == '{')
            {
                ++open;
            }
            else if (lineTrimmed[i] == '}')
            {
                ++closed;
            }
        }

        indents += static_cast<int>(open) - static_cast<int>(closed);
    }

    return output;
}

std::string SuperEnumConverter::PrintEnumConverter(int indents)
{
    if (m_converterType == SuperEnumConverterType::Standard)
    {
        return PrintEnumConverterStandard(indents);
    }
    else if (m_converterType == SuperEnumConverterType::BitFlag)
    {
        return PrintEnumConverterBitflag(indents);
    }

    Log::Error("The enum converter type is not supported. "
        "Please create an implementation for: " + ESuperEnumConverterType::ToString(m_converterType),
        "SuperEnumConverter::PrintEnumConverter(int)");
    return PrintEnumConverterStandard(indents);
}

std::string SuperEnumConverter::PrintEnumConverterStandard(int indents)
{
    std::string output = {};

    // Comment
    if (m_enumComment.Parsed)
    {
        output += PrintSingleComment(m_enumComment.Value, indents);
    }
    else
    {
        std::string generatedComment = "Converts between " + m_left.Type + " and " + m_right.Type;
        output += PrintSingleComment(generatedComment, indents);
    }

    // Class open
    output += PrintIndents(indents) + "class " + m_enumConverterName.Value + "\n";
    output += PrintIndents(indents) + "{\n";
    output += PrintIndents(indents) + "public:\n";
    ++indents;

    output += PrintIndents(indents) + "/// <summary>\n";
    output += PrintIndents(indents) + "/// Converts from the enum " + PrintEnumPrefixIfAny(false) + m_right.Type + " to " + PrintEnumPrefixIfAny(true) + m_left.Type + "\n";
    output += PrintIndents(indents) + "/// </summary>\n";
        
    output += PrintIndents(indents) + "static " + m_left.Type + " Convert(" + m_right.Type + " input)\n";
    output += PrintIndents(indents) + "{\n";
    ++indents;
        output += PrintIndents(indents) + "switch(input)\n";
        output += PrintIndents(indents) + "{\n";
        ++indents;
        for (const std::shared_ptr<Conversion>& conversion : m_allConversions)
        {
            output += PrintIndents(indents) + "case " + PrintEnumPrefixIfAny(false) +  conversion->Right + ": return " + PrintEnumPrefixIfAny(true) + conversion->Left + ";\n";
        }
        if (m_defaultValue)
        {
            output += PrintIndents(indents) + "default: return " + PrintEnumPrefixIfAny(true) + m_defaultValue->Left + ";\n";
        }
        --indents;
        output += PrintIndents(indents) + "}\n";

    // Consider adding a log in the cases where default is used.
    if (!m_defaultValue)
    {
        output += "\n" + PrintIndents(indents) + "return " + PrintEnumPrefixIfAny(true) + m_allConversions.at(0)->Left + ";\n";
    }
    --indents;
    output += PrintIndents(indents) + "}\n";

    // Then do the reverse.
    output += PrintIndents(indents) + "\n";
    output += PrintIndents(indents) + "/// <summary>\n";
    output += PrintIndents(indents) + "/// Converts from the enum " + PrintEnumPrefixIfAny(true) + m_left.Type + " to " + PrintEnumPrefixIfAny(false) + m_right.Type + "\n";
    output += PrintIndents(indents) + "/// </summary>\n";
    output += PrintIndents(indents) + "static " + m_right.Type + " Convert(" + m_left.Type + " input)\n";
    output += PrintIndents(indents) + "{\n";
    ++indents;
    output += PrintIndents(indents) + "switch(input)\n";
    output += PrintIndents(indents) + "{\n";
    ++indents;
    for (const std::shared_ptr<Conversion>& conversion : m_allConversions)
    {
        output += PrintIndents(indents) + "case " + PrintEnumPrefixIfAny(true) + conversion->Left + ": return " + PrintEnumPrefixIfAny(false) + conversion->Right + ";\n";
    }
    if (m_defaultValue)
    {
        output += PrintIndents(indents) + "default: return " + PrintEnumPrefixIfAny(false) + m_defaultValue->Right + ";\n";
    }
    --indents;
    output += PrintIndents(indents) + "}\n";

    // Consider adding a log in the cases where default is used.
    if (!m_defaultValue)
    {
        output += "\n" + PrintIndents(indents) + "return " + PrintEnumPrefixIfAny(false) + m_allConversions.at(0)->Right + ";\n";
    }
    --indents;
    output += PrintIndents(indents) + "}\n";

    // Class close
    --indents;
    output += PrintIndents(indents) + "};\n";
    return output;
}

std::string SuperEnumConverter::PrintEnumConverterBitflag(int indents)
{
    std::string output = {};

    // Comment
    if (m_enumComment.Parsed)
    {
        output += PrintSingleComment(m_enumComment.Value, indents);
    }
    else
    {
        std::string generatedComment = "Converts between " + m_left.Type + " and " + m_right.Type;
        output += PrintSingleComment(generatedComment, indents);
    }

    // Class open
    output += PrintIndents(indents) + "class " + m_enumConverterName.Value + "\n";
    output += PrintIndents(indents) + "{\n";
    output += PrintIndents(indents) + "public:\n";
    ++indents;

    {
        output += PrintIndents(indents) + "/// <summary>\n";
        output += PrintIndents(indents) + "/// Converts from the enum " + PrintEnumPrefixIfAny(false) + m_right.Type + " to " + PrintEnumPrefixIfAny(true) + m_left.Type + "\n";
        output += PrintIndents(indents) + "/// </summary>\n";
        output += PrintIndents(indents) + "/// <remarks>\n";
        output += PrintIndents(indents) + "/// This method is built to work independent of the super enum methods to enable conversation from external enums to internal.\n";
        output += PrintIndents(indents) + "/// Therefore some methods are duplicated and some implementation more explicit as it is unknown as to whether the enums requested\n";
        output += PrintIndents(indents) + "/// are super enums.\n";
        output += PrintIndents(indents) + "/// </remarks>\n";

        output += PrintIndents(indents) + "static " + m_left.Type + " Convert(" + m_right.Type + " input)\n";
        output += PrintIndents(indents) + "{\n";
        ++indents;

        if (m_defaultValue)
        {
            output += PrintIndents(indents) + "if(input == " + PrintEnumPrefixIfAny(false) + m_defaultValue->Right + ")\n";
            output += PrintIndents(indents) + "{\n";
            ++indents;
            output += PrintIndents(indents) + "return " + PrintEnumPrefixIfAny(true) + m_defaultValue->Left + ";\n";
            --indents;
            output += PrintIndents(indents) + "}\n\n";
        }

        // Setup the return value.
        if (m_defaultValue)
        {
            output += PrintIndents(indents) + m_left.Type + " returnNewValue = " + PrintEnumPrefixIfAny(true) + m_defaultValue->Left + "; \n";
        }
        else
        {
            output += PrintIndents(indents) + m_left.Type + " returnNewValue = " + PrintEnumPrefixIfAny(true) + m_allConversions.at(0)->Left + "; \n";
        }

        for (const std::shared_ptr<Conversion>& conversion : m_allConversions)
        {
            output += PrintIndents(indents) + "if(HasFlag(input, " + PrintEnumPrefixIfAny(false) + conversion->Right + "))\n";
            output += PrintIndents(indents) + "{\n";
            ++indents;
                //output += PrintIndents(indents) + "returnNewValue |= " + PrintEnumPrefixIfAny(true) + conversion->Left + ";\n";
                output += PrintIndents(indents) + "returnNewValue = static_cast<" + m_left.Type + ">(returnNewValue | " + PrintEnumPrefixIfAny(true) + conversion->Left + ");\n";
                
            --indents;
            output += PrintIndents(indents) + "}\n\n";
        }

        // End of the method return the value.
        output += PrintIndents(indents) + "return returnNewValue;\n";

        --indents;
        output += PrintIndents(indents) + "}\n";
    }

    output += PrintIndents(indents) + "\n";
    {
        output += PrintIndents(indents) + "/// <summary>\n";
        output += PrintIndents(indents) + "/// Converts from the enum " + PrintEnumPrefixIfAny(true) + m_left.Type + " to " + PrintEnumPrefixIfAny(false) + m_right.Type + "\n";
        output += PrintIndents(indents) + "/// </summary>\n";
        output += PrintIndents(indents) + "/// <remarks>\n";
        output += PrintIndents(indents) + "/// This method is built to work independent of the super enum methods to enable conversation from external enums to internal.\n";
        output += PrintIndents(indents) + "/// Therefore some methods are duplicated and some implementation more explicit as it is unknown as to whether the enums requested\n";
        output += PrintIndents(indents) + "/// are super enums.\n";
        output += PrintIndents(indents) + "/// </remarks>\n";

        output += PrintIndents(indents) + "static " + m_right.Type + " Convert(" + m_left.Type + " input)\n";
        output += PrintIndents(indents) + "{\n";
        ++indents;

        if (m_defaultValue)
        {
            output += PrintIndents(indents) + "if(input == " + PrintEnumPrefixIfAny(true) + m_defaultValue->Left + ")\n";
            output += PrintIndents(indents) + "{\n";
            ++indents;
            output += PrintIndents(indents) + "return " + PrintEnumPrefixIfAny(false) + m_defaultValue->Right + ";\n";
            --indents;
            output += PrintIndents(indents) + "}\n\n";
        }

        // Setup the return value.
        if (m_defaultValue)
        {
            output += PrintIndents(indents) + m_right.Type + " returnNewValue = " + PrintEnumPrefixIfAny(false) + m_defaultValue->Right + "; \n";
        }
        else
        {
            output += PrintIndents(indents) + m_right.Type + " returnNewValue = " + PrintEnumPrefixIfAny(false) + m_allConversions.at(0)->Right + "; \n";
        }

        for (const std::shared_ptr<Conversion>& conversion : m_allConversions)
        {
            output += PrintIndents(indents) + "if(HasFlag(input, " + PrintEnumPrefixIfAny(true) + conversion->Left + "))\n";
            output += PrintIndents(indents) + "{\n";
            ++indents;
            output += PrintIndents(indents) + "returnNewValue = static_cast<" + m_right.Type + ">(returnNewValue | " + PrintEnumPrefixIfAny(false) + conversion->Right + ");\n";

            --indents;
            output += PrintIndents(indents) + "}\n\n";
        }

        // End of the method return the value.
        output += PrintIndents(indents) + "return returnNewValue;\n";

        --indents;
        output += PrintIndents(indents) + "}\n";
    }

    output += PrintIndents(indents) + "\n";
    output += PrintIndents(indents) + "private:\n\n";

    ++indents;
        output += PrintIndents(indents) + "/// <summary>\n";
        output += PrintIndents(indents) + "/// Test to see whether value has the given flag.\n";
        output += PrintIndents(indents) + "/// </summary>\n";
        output += PrintIndents(indents) + "/// <param name=\"origin\">Origin to look for flag in. </param>\n";
        output += PrintIndents(indents) + "/// <param name=\"lookFor\">Value to look for. </param>\n";
        output += PrintIndents(indents) + "/// <returns>True means has flag. </returns>\n";
        output += PrintIndents(indents) + "static bool HasFlag(" + m_left.Type + " origin, " + m_left.Type + " lookFor)\n";
        output += PrintIndents(indents) + "{\n";
        ++indents;
            if (m_defaultValue)
            {
                output += PrintIndents(indents) + "return (origin & lookFor) != "+ PrintEnumPrefixIfAny(true) + m_defaultValue->Left + ";\n";
            }
            else
            {
                output += PrintIndents(indents) + "return (origin & lookFor) != "+ PrintEnumPrefixIfAny(true) + m_allConversions.at(0)->Left + ";\n";
            }
        --indents;
        output += PrintIndents(indents) + "}\n\n";

        output += PrintIndents(indents) + "/// <summary>\n";
        output += PrintIndents(indents) + "/// Test to see whether value has the given flag.\n";
        output += PrintIndents(indents) + "/// </summary>\n";
        output += PrintIndents(indents) + "/// <param name=\"origin\">Origin to look for flag in. </param>\n";
        output += PrintIndents(indents) + "/// <param name=\"lookFor\">Value to look for. </param>\n";
        output += PrintIndents(indents) + "/// <returns>True means has flag. </returns>\n";
        output += PrintIndents(indents) + "static bool HasFlag(" + m_right.Type + " origin, " + m_right.Type + " lookFor)\n";
        output += PrintIndents(indents) + "{\n";
        ++indents;
        if (m_defaultValue)
        {
            output += PrintIndents(indents) + "return (origin & lookFor) != " + PrintEnumPrefixIfAny(false) + m_defaultValue->Right + ";\n";
        }
        else
        {
            output += PrintIndents(indents) + "return (origin & lookFor) != " + PrintEnumPrefixIfAny(false) + m_allConversions.at(0)->Right + ";\n";
        }
        --indents;
        output += PrintIndents(indents) + "}\n";

    // Class close
    --indents;
    output += PrintIndents(indents) + "};\n";
    return output;
}

std::string SuperEnumConverter::PrintEnumPrefixIfAny(bool left)
{
    if (left && m_left.UseTypeAsPrefix)
    {
        return m_left.Type + "::";
    }
    else if (m_right.UseTypeAsPrefix)
    {
        return m_right.Type + "::";
    }

    return {};
}

std::string SuperEnumConverter::PrintSingleComment(const std::string& rawComment, int indents)
{
    std::string output = {};
    if (rawComment.empty())
    {
        return output;
    }

    output += PrintIndents(indents) + "/// <summary>\n";
    std::vector<std::string> lines = StringHelpers::Split(rawComment, "\n");
    for (const std::string& line : lines)
    {
        std::string lineTrimmed = StringHelpers::Trim(line);
        if (lineTrimmed != "")
        {
            output += PrintIndents(indents) + "/// " + lineTrimmed + "\n";
        }
    }
    output += PrintIndents(indents) + "/// </summary>\n";

    return output;
}