#pragma once
#include <vector>
#include <string>


// +------------------------------+
// Generated by SuperGenerator as an
// SuperEnum. See Tools for details.
// +------------------------------+
namespace SuperGameTools
{
    /// <summary>
    /// Defines the name for each panel registered to the panel selection manager.
    /// </summary>
    enum class PanelSelectionName : uint8_t
    {
        None,

        AssetBrowser,

        GameViewport,

        InspectorWindow,

        LoggerOutput,

        SceneHierarchy,

        ToolsViewport,

        ProjectProperties,

        ViewportToolsUndocked,

        ViewportToolsSettings,
    };

    /// <summary>
    /// Accompanies enums to provide extra functionality.
    /// </summary>
    class EPanelSelectionName
    {
    public:
        static PanelSelectionName Min() { return PanelSelectionName::None; }
        static PanelSelectionName Max() { return PanelSelectionName::ViewportToolsSettings; }

        static PanelSelectionName* ToArray()
        {
            static PanelSelectionName returnArray[] =
            {
                PanelSelectionName::None,
                PanelSelectionName::AssetBrowser,
                PanelSelectionName::GameViewport,
                PanelSelectionName::InspectorWindow,
                PanelSelectionName::LoggerOutput,
                PanelSelectionName::SceneHierarchy,
                PanelSelectionName::ToolsViewport,
                PanelSelectionName::ProjectProperties,
                PanelSelectionName::ViewportToolsUndocked,
                PanelSelectionName::ViewportToolsSettings,
            };
            
            return returnArray;
        }

        static std::vector<PanelSelectionName> ToVector()
        {
            static std::vector<PanelSelectionName> returnVector =
            {
                PanelSelectionName::None,
                PanelSelectionName::AssetBrowser,
                PanelSelectionName::GameViewport,
                PanelSelectionName::InspectorWindow,
                PanelSelectionName::LoggerOutput,
                PanelSelectionName::SceneHierarchy,
                PanelSelectionName::ToolsViewport,
                PanelSelectionName::ProjectProperties,
                PanelSelectionName::ViewportToolsUndocked,
                PanelSelectionName::ViewportToolsSettings,
            };
            
            return returnVector;
        }

        static std::vector<std::string> ToVectorValues()
        {
            static std::vector<std::string> returnVector =
            {
                "None",
                "AssetBrowser",
                "GameViewport",
                "InspectorWindow",
                "LoggerOutput",
                "SceneHierarchy",
                "ToolsViewport",
                "ProjectProperties",
                "ViewportToolsUndocked",
                "ViewportToolsSettings",
            };
            
            return returnVector;
        }

        static std::string* ToArrayValues()
        {
            static std::string returnArray[] =
            {
                "None",
                "AssetBrowser",
                "GameViewport",
                "InspectorWindow",
                "LoggerOutput",
                "SceneHierarchy",
                "ToolsViewport",
                "ProjectProperties",
                "ViewportToolsUndocked",
                "ViewportToolsSettings",
            };
            
            return returnArray;
        }

        static std::string ToString(PanelSelectionName value)
        {
            switch (value)
            {
                case PanelSelectionName::None: return "None";
                case PanelSelectionName::AssetBrowser: return "AssetBrowser";
                case PanelSelectionName::GameViewport: return "GameViewport";
                case PanelSelectionName::InspectorWindow: return "InspectorWindow";
                case PanelSelectionName::LoggerOutput: return "LoggerOutput";
                case PanelSelectionName::SceneHierarchy: return "SceneHierarchy";
                case PanelSelectionName::ToolsViewport: return "ToolsViewport";
                case PanelSelectionName::ProjectProperties: return "ProjectProperties";
                case PanelSelectionName::ViewportToolsUndocked: return "ViewportToolsUndocked";
                case PanelSelectionName::ViewportToolsSettings: return "ViewportToolsSettings";
            }
            
            return "None";
        }

        static PanelSelectionName FromString(const std::string& value, bool checkCase = true)
        {
            if (checkCase)
            {
                if (value == "None") return PanelSelectionName::None;
                if (value == "AssetBrowser") return PanelSelectionName::AssetBrowser;
                if (value == "GameViewport") return PanelSelectionName::GameViewport;
                if (value == "InspectorWindow") return PanelSelectionName::InspectorWindow;
                if (value == "LoggerOutput") return PanelSelectionName::LoggerOutput;
                if (value == "SceneHierarchy") return PanelSelectionName::SceneHierarchy;
                if (value == "ToolsViewport") return PanelSelectionName::ToolsViewport;
                if (value == "ProjectProperties") return PanelSelectionName::ProjectProperties;
                if (value == "ViewportToolsUndocked") return PanelSelectionName::ViewportToolsUndocked;
                if (value == "ViewportToolsSettings") return PanelSelectionName::ViewportToolsSettings;
            }
            else
            {
                std::string valueLower = ToLower(value); 
                if (valueLower == "none") return PanelSelectionName::None;
                if (valueLower == "assetbrowser") return PanelSelectionName::AssetBrowser;
                if (valueLower == "gameviewport") return PanelSelectionName::GameViewport;
                if (valueLower == "inspectorwindow") return PanelSelectionName::InspectorWindow;
                if (valueLower == "loggeroutput") return PanelSelectionName::LoggerOutput;
                if (valueLower == "scenehierarchy") return PanelSelectionName::SceneHierarchy;
                if (valueLower == "toolsviewport") return PanelSelectionName::ToolsViewport;
                if (valueLower == "projectproperties") return PanelSelectionName::ProjectProperties;
                if (valueLower == "viewporttoolsundocked") return PanelSelectionName::ViewportToolsUndocked;
                if (valueLower == "viewporttoolssettings") return PanelSelectionName::ViewportToolsSettings;
            }
            
            return PanelSelectionName::None;
        }
    
 private:

        /// <summary>
        /// Converts to lower. Copy from StringHelpers to ensure Enum does not require
        /// any outside dependency. Although we could include a header, doing so restricts
        /// the project which holds StringHelpers.
        /// </summary>
        static std::string ToLower(const std::string & input)
        {
            std::string output = input;
            for (char& c : output)
            {
                if (c >= 'A' && c <= 'Z')
                {
                    c = c - 'A' + 'a';
                }
            }
            return output;
        }
    };
}
